### ISSUE TITLE
item collector/sludge

### ISSUE THREAD

**Issue by marrokos** [Dysoch/DyTech#173]
hi, i m using all the last versions and fmod:

- item collector is colecting items if 2 underground belts touch each other:
![123456](https://cloud.githubusercontent.com/assets/9400086/4781710/c76e65c2-5cb9-11e4-89dd-9d8793c9b28b.jpg)

-the sludge gives tooooo many stone, needs rebalance...

thanks for the great mod

**Comment by Dysoch** [comment]
sludge will be changed in the future, and the collectors as well
