### ISSUE TITLE
Productivity Modules lvl 4+ are not allowed for "dytech indermediates"

### ISSUE THREAD

**Issue by cybervantyz** [Dysoch/DyTech#190]
For example, Stone Gears can be produced with Productivity Module 3, but not with 4, 5, 6, 7 or 8.
Same issue with Iron Gears, Advanced Electronic Circuits, Bundled Wires, Resin, Rubber Seeds etc

Also (I'm not sure if it's Dytech or vanilla issue) productivity modules are not allowed at all for some intermediate products - for example for wood, red wire and green wire.

**Comment by Dysoch** [comment]
if this still persists in next version, i will add a seperate list of the DyTech intermediates with the same things as the base list, to make sure it applies to them. (it should)
