### ISSUE TITLE
Research for mining drills (mk2+) and both furnaces (mk2+) Not showing up.

### ISSUE THREAD

**Issue by MrDrummer** [Dysoch/DyTech#191]
Basically, the research option for both furnace types and mining drills do not show up.
I have done the command to research all, and they don't appear in the crafting place, i can access them by 'game.player.insert' though,

I am using factorio 0.10.12 and DyTech Automation 1.2.0.
Seems to me like a bug.

Factorio forums said that 1.2.0 can be used with 0.10.x

**Comment by Dysoch** [comment]
you are probably using Dynamic?

**Comment by Dysoch** [comment]
not a bug, and will be changed to work differently next version
