### ISSUE TITLE
accumulator Mk VI cannot be made of assembling machine

### ISSUE THREAD

**Issue by coelun** [Dysoch/DyTech#196]
accumulator Mk VI cant make. in assembling machine.
accumulator Mk VI  need 110 battery and others , but Battery stack limit 100.
battery can not be put in the Assembling machine.

factorio 0.11.6
Dytech-Enelgy 1.5.0
Dytech-Warfare 2.1.0
Dytech-Core 0.13.3
Treefarm-Mod 1.2.4
endless-resources 0.3.0
AlianPlant 0.1.0
Dytech-Logistic 1.3.0
Dytech-Metallurgy 2.1.0
Dytech-Modules 1.3.0
Dytech-Storage 1.4.0
Dytech-Transportation 1.3.0
Dytech-Inserters 1.2.0
Dytech-Warfare 2.1.0

**Comment by coelun** [comment]
I changed this. Running.  thank you. :D

DyTech-Inserters_1.2.0.zip\DyTech-Inserters\prototypes\recipe\inserter-dytech.lua
line 58
-     {"fast-inserter", 1},

DyTech-Warfare_2.1.0.zip\DyTech-Warfare\prototypes\base-edit\item.lua
line 6
-data.raw["item"]["battery"].stack_size = 100
+data.raw["item"]["battery"].stack_size = 200

**Comment by Dysoch** [comment]
fixed in the newest version of dytech (not released)

**Comment by coelun** [comment]
cant make Very Fast inserter by Assembling machine.

MAIN-DyTech-Machine_1.0.1
