### ISSUE TITLE
Centrifuge Carbon Production Crashes Game

### ISSUE THREAD

**Issue by Cheata** [Dysoch/DyTech#197]
Iv been having problems with the Carbon Production in the Centrifuges,  Frenquently the centrifuges seem to break when producing Carbon,  They stop outputting Carbon and only output Sulfur. When this happens clicking on the centrifuge to view its production causes the game to crash.  demolishing and rebuilding the centrifuge fixes the issue untill it occures again...

This only occurs when producing carbon.

In particular this seems to occur when i load a saved game.

**Comment by Dysoch** [comment]
mmm i will have to test it when i finished remaking Metallurgy

**Comment by Cheata** [comment]
Considering the bug report is based on the "Old" version of the Dytech mod probably best to ignore it until i can confirm if it is still occuring in the new version. :)

**Comment by Dysoch** [comment]
Carbon making is currently not in Metallurgy, but will be eventually. Till then ill leave this open
