### ISSUE TITLE
Item collector crash

### ISSUE THREAD

**Issue by Muchaszewski** [Dysoch/DyTech#199]
![image](https://cloud.githubusercontent.com/assets/5092066/5569104/71e902f4-8f6a-11e4-8058-b806245fb317.png)
- Like on picture. Game will crush with setup like this.
- Item collector dont pickup items at all (only general one) if game didnt crash
Using only DyTech, github version. Factioro 0.11.5

**Comment by RegDenied** [comment]
This is a duplicate of  #184
