### ISSUE TITLE
DyTech Inserter does not work

### ISSUE THREAD

**Issue by jordan30001** [Dysoch/DyTech#201]
On SP factorio (V0.11.6-2) with DyTech-Core 0.13.3 and DyTech-Inserters 1.2.0 the DyTech Inserter does not work (the one that keeps up with the super transport belt)

tested scenarios:
track->track
chest->track
track->chest
chest->chest

further testing shows that the DyTech Inserter Fast for the extreme belt does work though

**Comment by RegDenied** [comment]
Works for me. Could it be that you just didn't add a filter, the Dytech Inserter is a smart inserter.
