### ISSUE TITLE
High Speed Train seems to loose path

### ISSUE THREAD

**Issue by ocbaker** [Dysoch/DyTech#202]
Hey,

I was going to try using a high speed train for a very long distance Copper deposit that I wanted to mine, (See (Copper at top): http://i.imgur.com/w5ATowJ.png)

However is would loose it's path all the time. Simply stopping and starting the trains path would fix the issue. I switched to a normal train and it pathed fine with no issues.

**Comment by Dysoch** [comment]
will be fixed in the next version of factorio

**Comment by geostyx** [comment]
0.11.11 fixed this.

**Comment by Dysoch** [comment]
yup, closed
