### ISSUE TITLE
error loading the game with dytech mods HELP

### ISSUE THREAD

**Issue by IndoCanadian** [Dysoch/DyTech#204]
I am using Dytech 
DyTech-Core
DyTech-Automation
DyTech-Transportion 
DyTech Energy
DyTech Inserters 
DyTech Logistic 
DyTech modules 
DyTech storage 
DyTech tools 
My Game is running on 0.11.7 
i have an error saying 
1699874.013852  Info Logger.cpp:148: 2014:12:31 13:23:00; Factorio 0.11.7 (Build 12875, win32)
1699874.559292  Info ModManager.cpp:204: Loading mod core 0.0.0 (data.lua)
1699874.592147  Info ModManager.cpp:204: Loading mod base 0.11.7 (data.lua)
1699875.143946  Info ModManager.cpp:204: Loading mod DyTech-Core 0.13.3 (data.lua)
1699876.096681  Info ModManager.cpp:204: Loading mod DyTech-Energy 1.5.0 (data.lua)
1699877.160768  Info ModManager.cpp:204: Loading mod DyTech-Logistic 1.3.0 (data.lua)
1699877.809637  Info ModManager.cpp:204: Loading mod DyTech-Modules 1.3.0 (data.lua)
1699878.523259  Info ModManager.cpp:204: Loading mod DyTech-Storage 1.4.0 (data.lua)
1699879.258221  Info ModManager.cpp:204: Loading mod DyTech-Tools 2.2.0 (data.lua)
1699879.979731  Info ModManager.cpp:204: Loading mod DyTech-Transportation 1.3.0 (data.lua)
1699880.758931  Info ModManager.cpp:204: Loading mod DyTech-Automation 1.3.2 (data.lua)
1699881.854353  Info ModManager.cpp:204: Loading mod DyTech-Inserters 1.2.0 (data.lua)
1699882.764099  Info ModManager.cpp:204: Loading mod base 0.11.7 (data-updates.lua)
1699885.225431  Error Util.cpp:37: Error while loading entity prototype "roboport-2" (roboport): No such node (base_patch)
Modifications: DyTech-Logistic

plz help

**Comment by Dysoch** [comment]
Will be fixed in a few hours.
