### ISSUE TITLE
Factorio 11.9 - Science Pack 1 missing Prerequisite ID

### ISSUE THREAD

**Issue by DerivePi** [Dysoch/DyTech#205]
Just upgraded to latest version, 11.9, and the loading stopped with an error regarding the empty ID for Science Pack 1 prerequisite (was previously working under other version).  Went to Dytech Core/Prototypes/Technology/Science.lua and deleted the empty prerequisite line for science pack 1 (line 7 I believe).

**Comment by tmoore79** [comment]
That happened with me too. DerivePi did that help?

**Comment by DerivePi** [comment]
Sorry, yes.  Deleting the empty prerequisite line works.

**Comment by RegDenied** [comment]
Still persistent with Factorio 11.10 and Dytech-Core 13.4

**Comment by vaendryl** [comment]
I downloaded the latest version of factorio and the mod files today and I also had this problem loading the game. at 2% it shows this message: http://i.imgur.com/kAbIwa0.png
deleting line 7 as mentioned before has now allowed me to start the game.

**Comment by Dysoch** [comment]
no longer needed, as science packs are no longer in the mod
