### ISSUE TITLE
Factorio Crash on Load "Dytech-inserter has wrong insert vector"

### ISSUE THREAD

**Issue by Mrkeserian** [Dysoch/DyTech#206]
Morning all, having a rough time getting dytech latest to load. Current mod list:

88838.625123  Info Logger.cpp:148: 2015:01:07 08:59:08; Factorio 0.11.10 (Build 13013, win64)
88839.162869  Info ModManager.cpp:204: Loading mod core 0.0.0 (data.lua)
88839.177582  Info ModManager.cpp:204: Loading mod base 0.11.10 (data.lua)
88839.430595  Info ModManager.cpp:204: Loading mod DyTech-Core 0.13.4 (data.lua)
88839.694159  Info ModManager.cpp:204: Loading mod DyTech-Energy 1.5.1 (data.lua)
88839.994601  Info ModManager.cpp:204: Loading mod DyTech-Logistic 1.3.1 (data.lua)
88840.316636  Info ModManager.cpp:204: Loading mod DyTech-Metallurgy 2.1.1 (data.lua)
88840.703398  Info ModManager.cpp:204: Loading mod DyTech-Modules 1.3.1 (data.lua)
88841.095575  Info ModManager.cpp:204: Loading mod DyTech-Storage 1.4.1 (data.lua)
88841.495638  Info ModManager.cpp:204: Loading mod DyTech-Transportation 1.3.1 (data.lua)
88841.916191  Info ModManager.cpp:204: Loading mod DyTech-Automation 1.3.3 (data.lua)
88842.375780  Info ModManager.cpp:204: Loading mod DyTech-Inserters 1.2.1 (data.lua)
88842.864244  Info ModManager.cpp:204: Loading mod DyTech-Warfare 2.1.1 (data.lua)
88843.424357  Info ModManager.cpp:204: Loading mod base 0.11.10 (data-updates.lua)
88844.836875  Error Util.cpp:37: dytech-inserter has wrong insert vector as it isn't in safe distance from the tile edge.

Looks like something is FUBAR'd in Dytech-Inserters, but my LUA and knowledge of Factorio isn't quite good enough to figure out what it is.

**Comment by RegDenied** [comment]
I removed all the "dytech-inserter" content of the .lua files and got the same error for the "dytech-inserter-fast", then I removed the "super-inserter.lua" files all together and its calling for it and got the error for the non super "inserter-close".

The the value for "insert_position" (which I suspect is meant by "insert vector") in the .lua files for the inserters seem fine to me. 

Maybe this is a factorio and not an actual dytech issue?!

**Comment by Dysoch** [comment]
there is a fix in the forum, and the newest dev build has already been fixed
