### ISSUE TITLE
DyTech Core not loading (science-packs-1   empty id)

### ISSUE THREAD

**Issue by Denation** [Dysoch/DyTech#208]
What i use:
Factorio  MS Windows (64 bit exe installer)   0.11.10 (alpha)
"DyTech-Core_0.13.3"

when i aktivate core alone it comes
"
Error while loding technology prototype "sciece-packs-1"
(technology): Empty id of technology prerequisite.
Modifications: DyTech-Core
"

Ps.: oh i forgot i test the other cores for 11.x whith the same results

**Comment by Marduke** [comment]
this error is apear in 0.11.9 and 0.11.10 in my case. 0.11.8 works good. (i use 1.9.9 version)

**Comment by Dysoch** [comment]
has already been fixed in the newest dev build. You can search the DyTech Forum for a player made fix
