### ISSUE TITLE
treefarm+rubberwood

### ISSUE THREAD

**Issue by fidschi** [Dysoch/DyTech#218]
rubberwood if it grows on the tree farm it comes to desync in mp probably grow at

**Comment by fidschi** [comment]
I think I've found the problem in the control.lua and in the tree.lua are the same program line by line I deleted the mahl in the control.lua and now it's beu us but I can only now test 2 hours dysoch you can there to watch?

**Comment by Dysoch** [comment]
Could you direct where you think you found the problem? Makes it easier for me to check it instead of checking every line

**Comment by fidschi** [comment]
actually to say exactly I do not know the exact
I just line by line 21-93 Erased well since it is but

We now have 3 tree farms for 4 hours passed with rubber and can no longer brobleme

**Comment by Dysoch** [comment]
should work now
