### ISSUE TITLE
Duplicate key name in DyTech-Core (v.1.0.0) / item-names.cfg

### ISSUE THREAD

**Issue by Keramo** [Dysoch/DyTech#221]
Factorio 0.11.13 throws an error at start:
![error](https://cloud.githubusercontent.com/assets/8777524/5874583/bd75249e-a303-11e4-8f7a-16ea94d25327.JPG)

Line 35 in "Core-DyTech-Core\locale\de\item-names.cfg" is (blue selected):
![error_source](https://cloud.githubusercontent.com/assets/8777524/5874615/111ce3de-a304-11e4-8c12-c2f92b6b648b.JPG)

After deletion of line 35 the program starts. Any side-effects?

(Sorry for my english, my german is better ;-) )

**Comment by Dysoch** [comment]
already fixed
