### ISSUE TITLE
Path _[CORE]Dytech-Core_/graphics/intermediates/advanced-processing-unit.png does not match any mod

### ISSUE THREAD

**Issue by Rikrik** [Dysoch/DyTech#222]
![image](https://cloud.githubusercontent.com/assets/1931058/5874685/e16a7858-a304-11e4-8bd4-8c65d7ea569f.png)

I just downloaded your new version with the fixed dependencies but i get this error when loading the game now.

**Comment by Rikrik** [comment]
It appears there are a few more files with this problem, when i manually fixed this and restarted factorio it gave the same message about steel gear wheels.

**Comment by Dysoch** [comment]
fixed it, will upload new version now. Download the new Machine
