### ISSUE TITLE
Cant connect to multiplayer Game

### ISSUE THREAD

**Issue by Grotznak** [Dysoch/DyTech#223]
My friend and I downloaded the newest Factorio (0.11.13) and Dytech (1.0.0) Version

Now we cant connect to a fresh new map.

After Dowloading the map the joining player gets instatly kicked out with
"Desync redownloading map"

this repeats indefinitly

**Comment by izofra** [comment]
same for me and my friends ++

**Comment by Crazierinzane** [comment]
Also cannot play multiplayer with friend.

What happens is that I join the game he is hosting and then the screen will continually flash between downloading the map, establishing a connection (I think,) and actually being in the game. During the short quarter of a second that I am in the game, I am able to move my character slightly.

Could probably open a menu if I was fast enough.

**Comment by MaxStrategy** [comment]
Same exact issue. Instant desync upon connecting then stuck in a loop of re-sending + dysyncing. The mod is really awesome and I've seen people play previous versions multiplayer, I hope it's playable soon.

**Comment by colt456** [comment]
I have the same issue with my game.  We connect for a second and then get the dysyncing loop.  We will keep checking for new update and will play as soon as possible.

**Comment by darkkenji1** [comment]
Hi guys any update On this? Or woworkaround in the mean time

**Comment by darkkenji1** [comment]
Hi guys any update On this? Or workaround in the mean time

**Comment by izofra** [comment]
dont know - will test to day

**Comment by Crazierinzane** [comment]
This needs to be prioritized.

**Comment by swoopko** [comment]
Hi all, any update at all? I am dying here to play this mod with my bro.

**Comment by MaxStrategy** [comment]
Has anyone got it working?

**Comment by Dysoch** [comment]
i will fix this right now. The issue persists with the interface between Treefarm and DyTech, even if it isnt installed.

**Comment by darkkenji1** [comment]
Legend!

**Comment by Dysoch** [comment]
should be fixed (should be really, but cant be sure)

**Comment by Grotznak** [comment]
Hi Dysoch,
Thank you very much for your great support 

When trying to host a Multiplayergame in 1.0.1
![mp_error_dytech](https://cloud.githubusercontent.com/assets/832224/5962819/dfff7824-a7e6-11e4-85fa-5d6278d8c1f3.png)

singleplayer works fine

**Comment by swoopko** [comment]
Same error here.

**Comment by darkkenji1** [comment]
Creating a map in single player saving it and loading it in as multiplayer will allow us to join the game, tested with 2 players on the map, but every 10-15 seconds we are getting desync, tested with all mod modules (Core,Power,War,Machine) hope this helps, we are still testing it

**Comment by rnovacek** [comment]
This fixed it for me, two players can connect the game. I haven't tested the gameplay yet.

https://github.com/rnovacek/DyTech/commit/edeae2a7e59a079c310c20865a4d51f3c1b4d511

**Comment by Grotznak** [comment]
>Creating a map in single player saving it and loading it in as multiplayer will allow us to join the game, >tested with 2 players on the map, but every 10-15 seconds we are getting desync, tested with all mod >modules (Core,Power,War,Machine) hope this helps, we are still testing it

This has worked for us (without any desyncs)

**Comment by darkkenji1** [comment]
we are playing with the file rnovacek provided, but I am afraid we are going to miss that resin on startup

**Comment by SuicidalKid** [comment]
@darkkenji1 
When that error message pops up, hit escape. It closes the error message and you can continue playing. Yay for temporary fixes!

**Comment by Dysoch** [comment]
Fixed, i hope :)

Make a new issue if it persists in the new version
