### ISSUE TITLE
Rubber don´t grow (SP)

### ISSUE THREAD

**Issue by MrEpeko** [Dysoch/DyTech#224]
Rubberseeds don´t grow, See in Topic :)

**Comment by Dysoch** [comment]
I will look into it. Probably missed a single line in the tree growing code that adds them to the list.

**Comment by MrEpeko** [comment]
i work in Moment with a trick 
edited the LUA File Counter from 1 to 500 every start  ;)

**Comment by SuicidalKid** [comment]
Rough est on patch? Cannot continue through the game without rubber.

**Comment by Dysoch** [comment]
its working in the current dev build. This issue has now been fixed.
