### ISSUE TITLE
Advanced-processing-unit.png does not match any mod.

### ISSUE THREAD

**Issue by scobby** [Dysoch/DyTech#225]
Hi,
a friend of mine, have this error:
he installed factorio new, removed the complete factorio folder from "Roaming" and downloaded the dytech mod 2x from the forum. Can you help?

He have version 0.11.13. Windows 64 bit.

I have the same configuration and it works like a charm!

![factorio_error](https://cloud.githubusercontent.com/assets/9264361/5879432/9ae6be2a-a32f-11e4-9835-7fb99403dc3e.gif)

**Comment by Dysoch** [comment]
this should already be fixed. Redownload DyTech-Machine from Github or the Forum, and this will no longer be an issue.
if for some reason it still is, reopen the issue
