### ISSUE TITLE
Frame Mk 1 Recipe Change

### ISSUE THREAD

**Issue by Dysoch** [Dysoch/DyTech#230]
Should require less iron, because now the basic mining drill has a to high iron usage in the recipe (98).
Should be around 40 to 50 iron

**Comment by hohounk** [comment]
I'm not sure if it is all that much of a problem. It requires tons of iron, yes, but so what? It gives more reason to not rush out of burner-miners as fast. I personally didn't even realize they cost as much in my first play with the newer DyTech :)

**Comment by Dysoch** [comment]
changed to require 78 iron instead of 98
