### ISSUE TITLE
Lava Heater & Cooler are not craftable

### ISSUE THREAD

**Issue by MrEpeko** [Dysoch/DyTech#232]
Lava Heater & Cooler are not craftable
it will be replace with a Luiquidhandler but this machine don´t accept Lava in the recipes.

i changed the Icons in LUA  (so in Metallurgy Recipes are shown the right png) but u get an simple Luiquidhandler maybe ist an issue with unknown-key entity
u can place an interact withe the Lava-machines if u place it in the mapeditor an play the edited map

hope that helps (sry 4 my bad engl. :) )
thy

**Comment by AShegar** [comment]
Quick tip: wrong "result" attribute in 
MAIN-DyTech-Machine_1.0.0\prototypes\metallurgy\lava\machines\recipe.lua

**Comment by MrEpeko** [comment]
i change the result but it doesn´t work

**Comment by hohounk** [comment]
You need to do */c game.player.force.resetrecipes()* in the console to make it work in a game you started before you modified the file.

**Comment by AShegar** [comment]
>> /c game.player.force.resetrecipes()
I'm  changed it without any console commands... 
@MrEpeko - what values do you put instead? They should be "lava-cooler" and "lava-heater"

**Comment by MrEpeko** [comment]
ok the ingame command works ty (it was the first time i used a command in console)
i look now for the right working

**Comment by Dysoch** [comment]
fixed for next version
