### ISSUE TITLE
Can't insert ores into forge

### ISSUE THREAD

**Issue by hohounk** [Dysoch/DyTech#234]
After fixing the lava heaters as described on #232 I'm now pumping 1200C lava to my blast furnace. What I can't do is insert any sort of ores there. I tried manually entering. Shift-click didn't do anything. Trying to manually place it in any input slots I get "Copper ore cannot be smelted", I got same message with any item I tried to enter. E.g wooden chest. I also tried "piping" in via belts (just had belt facing the furnace) and normal/double length inserters. Nothing worked.

I *was* able to manually insert copper ore to two of the first result slots. It had no effect, though.

What am I missing here?

**Comment by hohounk** [comment]
I made a typo in the bug report. I was meaning it was not possible to insert ores into *blast furnace*. Obviously I tested with blast furnace but just in case I also tried out forge. Neither accepted ores.

**Comment by AShegar** [comment]
@Dysoch - Sorry, but what's a rough estimate to fix it? It's really hard go further without blast furnaces :)

**Comment by Dysoch** [comment]
tomorrow this will be fixed

**Comment by AShegar** [comment]
Thank you so much!

**Comment by Dysoch** [comment]
If you could supply a savegame, that would make testing it easier :)

**Comment by Dysoch** [comment]
mmmm made a test scenario real quick. It doenst work, no matter what i do. I will try a few more things before i am making an official bug report to the devs

**Comment by Dysoch** [comment]
made an official bug report on the forum. This is not something i can fix.
If you have any more information, please report it here: 
http://www.factorioforums.com/forum/viewtopic.php?f=7&t=8319

**Comment by hohounk** [comment]
So, apparently it's not a bug but an intended functionality that won't likely be changed any time soon.
Does that mean you'll go back to assembler-based recipes?

Also, you are incredibly brave if you really did no testing before reworking the entire mod from assemblers to furnaces :o

**Comment by AShegar** [comment]
I think, it can be reverted to be an assembling machine (I already tested that variant), but it would entail wipe of current game-world... Is there any possibility to keep changes not so critical, but fix the issue?

**Comment by Dysoch** [comment]
No that is not possible. World wipe is necessary unfortunately. Bugfixes and Balance Release will be in a few hours

**Comment by Dysoch** [comment]
Ok, i found a way to keep your world with the new version

You have to start the game with metallurgy disabled in the data.lua file and load your world. If you placed some metallurgy machines, they will gone. Save the game and exit factorio. Go to data.lua and enable metallurgy again and start the game. Load your world and keep playing.

What you basically did then is remove the furnace type blast furnace from the game, and added the assembling type back. This works without errors

**Comment by Dysoch** [comment]
this has been fixed
