### ISSUE TITLE
Crystal Formations can't be mined by drills under Mk5

### ISSUE THREAD

**Issue by Rikrik** [Dysoch/DyTech#235]
It seems a bit out of balance, i need to mine the crystal formations to make better laser turrets, but i need a ton of ardite tools to manually mine them really slowly. Or a mining drill Mk5 which isn't very easy to get to, while biters and spitters keep getting stronger, and the one laser turret that doesn't require any gems can't reach the spitters.

**Comment by MrEpeko** [comment]
don´t Change pls, because u don´t need diamonds & co so early

**Comment by Cheata** [comment]
imho mk5 drill is a bit late, especially if your playing a death-world and focusing on combat tech personally i mod the drills file so that the mk3 has a mining strength of 8 and the mk 4 strength of 10 meaning that the mk3 is the first drill that can do crystal all be it really slowly.

**Comment by akerlaoncl** [comment]
Corpse processing is your friend.
Personally I just trap one biter spawner and create a mobfarm by surrounding it with laser turrets and walls so they don't kill the spawner but they kill all spawned biters. Adding belts outside the walls and using inserters to put the corpses in chests allows nearly unlimited amount of gems through corpse processing. Takes a while for the corpses to fill the walled area and finally spill over the wall to the belts, but after that your golden.
