### ISSUE TITLE
Enable productivity modules for gems and DyTech intermediates

### ISSUE THREAD

**Issue by tobyas** [Dysoch/DyTech#236]
DyTech intermediates should be enabled for productivity modules. Gems too, unless for balancing reasons. Currently only the vanilla recipes work with them. It might be possible to enable productivity modules for other groups of items. This is slightly similar to #190, though this applies for all productivity modules and for more recipes.

**Comment by Dysoch** [comment]
Added all intermediates to the productivity module list for next version. Plates are excluded, because you can use metallurgy for it. I dont know if Gems should be done aswell, but i did.
If i find it to overpowered, i will remove the gems from the list

**Comment by tobyas** [comment]
Nice. Not to sure about the balancing part. Just noticed that when I was playing I wanted to apply the productivity modules to gems, since gems being a limited resource they are one of the reasons the productivity stuff is in the game. Seemed kind of logical to me.
