### ISSUE TITLE
Slight imbalance for tech requirements

### ISSUE THREAD

**Issue by tobyas** [Dysoch/DyTech#238]
The modules level three, military four require alien tech, the following levels don't need it.
The battery tank needs a lasergun for building, but you don't have to research the lasergun before researching the battery tank tank.
The Liquid Automated Crafting technologies require only low amounts of level one and two science packs.

**Comment by Dysoch** [comment]
closing this issue, bu it isnt fixed yet. Adding this to trello (to do list) and will be fixed soon :D
