### ISSUE TITLE
Dirty Ore

### ISSUE THREAD

**Issue by penguineer** [Dysoch/DyTech#239]
When playing DyTech together with F-Mod until this upgrade, the game had a nice feature: Dirty Ores.
I liked the idea of cleaning the ore before it could be smelted.

However, after the update, the Mods do not get along (Foundry and Forge are now definied by both Mods) and the Dirty Ore is gone.

My questions:
* Is the fact that the dirty ore is gone a bug?
* If not, I would like put bring it back. Is there a chance that a Pull Request bringing back the Dirty Ore into DyTech will be accepted or is the feature not wanted?

**Comment by EurypteriD192** [comment]
I have tested with 11.13 and Dytech 1.0 
Dirty ore is not there in this version (only dytech installed no other mods)

**Comment by penguineer** [comment]
I had this with DyTech and F-Mod.

The remaining question is: Would this be a desirable feature for DyTech?

**Comment by Dysoch** [comment]
this will be brought back. probably in the next version. (not in the bugfix release)

**Comment by penguineer** [comment]
:)

Anything I can do to help?

**Comment by Dysoch** [comment]
nope :D Just wait patiently :D

**Comment by penguineer** [comment]
In a6fa066e92c0306642fc53c7ba60944b8cf132b4 there is a commit that would bring back ore cleaning. (Mostly taken from the "old" DyTech-Metallurgy with minor tweaks.)

I will try to add some graphics before creating a pull request:
* Recipe: Dirty Copper Ore Cleaning
* Recipe: Dirty Iron Ore Cleaning
* Recipe: Sludge Processing
* Entity/Item: Centrifuge
* Technology: Centrifuge Processing

However, comments are welcome. :)

**Comment by penguineer** [comment]
Preview :)

![centrifuge-preview-3](https://cloud.githubusercontent.com/assets/2039739/6255839/743ebbcc-b7b3-11e4-9b15-61956f43b7db.png)

**Comment by penguineer** [comment]
Animation Preview:


![centrifuge](https://cloud.githubusercontent.com/assets/2039739/6277641/9b0e9e60-b890-11e4-81b1-d37b8d81d72d.gif)

This is the first shot, the animation script needs some optimizing (shorter rotation time, slower water removal).

Also, there will be some more details to make the part look nicer. :)

**Comment by ddayver** [comment]
Great! I like this :)

**Comment by penguineer** [comment]
Centrifuge Promo Image:

![centrifuge-preview-10](https://cloud.githubusercontent.com/assets/2039739/6315201/ab646892-b9fa-11e4-87ca-030ed00f951a.png)

Animation is currently rendering (takes some time, though – even in small resolution). I am greatful for any hints on the camera angel and light/envionment settings.

**Comment by penguineer** [comment]
and the animation (Pixel artifacts come from gif creation.)

![centrifuge10](https://cloud.githubusercontent.com/assets/2039739/6318392/10cc0c2c-ba90-11e4-8555-5f1f1d753dd7.gif)

I need to sort out the shadows (Cycles does not support shadow-only. :( ), afterwards the sprite sheet will be created and the centrifuge can go to the mod.

**Comment by Dysoch** [comment]
NICE :D

**Comment by penguineer** [comment]
Almost done. :) d494b3e759d20398f2cd6518337e52e2ada51cc8

Open issues:
* northern pipes
* a sound

![centrifuge_sprites](https://cloud.githubusercontent.com/assets/2039739/6342007/31c48952-bbd2-11e4-8e93-c5963b2b71d6.gif)

**Comment by penguineer** [comment]
The sound is still missing but I wouldn't get around this for the next weeks. There was no sound before, so we are not loosing anything.
