### ISSUE TITLE
I cannot start when Dytech is installed

### ISSUE THREAD

**Issue by teenusa** [Dysoch/DyTech#241]
I think the title is saying most the whole problem .
some details:
I even have the problem with no modd. (with Dytech core only)
i have the newest version.
I tested it with Win8 Win8.1 Win10 preview 9926

a picture of the error:
![dytech](https://cloud.githubusercontent.com/assets/10729955/5924850/635feafc-a65f-11e4-8f1d-9a00162e500e.png)

I hope anyone can help me? Because Dytech is on of THE best mods :D

**Comment by Dysoch** [comment]
You must have edited the mod somehow

**Comment by Dysoch** [comment]
Brass-pipe-to-ground is not anywhere in the mod. (Doesnt exist) 

You are the only one with this issue, and i cant find

**Comment by teenusa** [comment]
That´s strange, because i did not edited the mod.
I kust downloaded it, and moved it in the mods folder.
maybe i downloaded the false Dytech_Core?
That´s the link i downloaded:
https://github.com/Dysoch/DyTech/releases/download/v2.0.0/CORE-DyTech-Core_1.0.0.zip
In the factorio forum.
I will install whole factorio a secound time new and we will see :D I will also download the mod a secound time maybe it will fix it :D 
(I hope so)
I will give you a statement in the next time.

**Comment by Dysoch** [comment]
seems weird this error. happens it again, make a new issue
