### ISSUE TITLE
heated Lava in Blast Furnace don´t save 

### ISSUE THREAD

**Issue by MrEpeko** [Dysoch/DyTech#242]
see Topic :) every relog the blast furnace are empty  btw 5k Intern-Buffer are to much,...  u can reduce them 

but don´t change the Sience-time it´s fantastic u have a lot more time :) 

greets

**Comment by Dysoch** [comment]
This is a factorio bug, if you have more information, please report it here:
http://www.factorioforums.com/forum/viewtopic.php?f=7&t=8320

**Comment by Dysoch** [comment]
will be fixed in the next version of factorio
