### ISSUE TITLE
DyTech-CORE Multiplayer ERROR

### ISSUE THREAD

**Issue by Lycrus** [Dysoch/DyTech#243]
New error when attempting to start a multiplayer map with DyTech installed.

Mods: Dytech (All modules) + Treefarm Lite

I made tests to exclude Treefarm and all modules. DyTech-CORE alone produces said Error. 

Picture:

http://postimg.org/image/hp850x8zz/

**Comment by Lycrus** [comment]
Reinstalled and tried again with everything being fresh, using same language as friend etc. Still doesnt work. I guess new DyTech version is just not muliplayer-ready

**Comment by Dysoch** [comment]
i know what is causing this. I can probably guess that nobody in your game is player 1? Only player 1 gets the resin. I will change this to work different, and without script

**Comment by Lycrus** [comment]
Indeed. We have custom names.

**Comment by Dysoch** [comment]
custom names dont matter, its the player that started the map that is set as player 1. if he/she is offline when a script is trying to insert something to player 1, the game crashes.

But anyway, this should no longer be an issue, fixed it with actual gameplay and no longer script wise.
closing issue
