### ISSUE TITLE
Can't Load Old Save after updating to 1.0.1

### ISSUE THREAD

**Issue by SuicidalKid** [Dysoch/DyTech#244]
Updated DyTech Core and Machine to 1.0.1 so I could use the rubber trees. Now I can't load my old save - (Note that when trying to load, it moves the selected save to the bottom one)
![save trying to load](https://cloud.githubusercontent.com/assets/10734162/5966044/eaa07dea-a7ce-11e4-98bc-428957293977.png)
![bug when tried to load](https://cloud.githubusercontent.com/assets/10734162/5966046/ecf20a96-a7ce-11e4-8258-f1e08dbe1b80.png)

**Comment by Dysoch** [comment]
i am closing this issue since obviously you cant read. check this post and apply the 8 steps described to make your save compatible
http://www.factorioforums.com/forum/viewtopic.php?f=43&t=6456&p=66109&sid=90b3fdf46edf839b95dd213a5afa5dda#p66109

**Comment by SuicidalKid** [comment]
Sorry, didn't see that link anywhere.
