### ISSUE TITLE
DyTech Core 1.0.1 + TreeFarm Lite 0.1.2

### ISSUE THREAD

**Issue by ddayver** [Dysoch/DyTech#245]
An error occurred while loading the game and after the generation of new:

http://s020.radikal.ru/i702/1501/84/79def91434cf.png

**Comment by drs9999** [comment]
Maybe it's because the allInOne-table defined in trees.lua is a local variable, you might can't access it in the control.lua. So making it global (simply removing the "local") might solve it, I haven't tested it, though...

**Comment by Lycrus** [comment]
Well, the error seems very similar to the one i postet hours ago and only occurs in multiplayer. I guess some code lines are kinda screwed up..

**Comment by ddayver** [comment]
"making it global allInOne" - it's work, thanks

**Comment by RegDenied** [comment]
Could you elaborate on which line in which file has to be changed? I could not find a trees.lua file. Thx

**Comment by ddayver** [comment]
/CORE-DyTech-Core_1.0.1/scripts/trees.lua

line 26:
local allInOne = {
replace
allInOne = {

**Comment by Dysoch** [comment]
i will fix this. Will probably release a new version tonight (no promise) and release a new tree as well :D

**Comment by Dysoch** [comment]
fixed
