### ISSUE TITLE
Error when planting Rubber Seed. (CORE 1.0.1)

### ISSUE THREAD

**Issue by GameveD** [Dysoch/DyTech#249]
When planting Rubber Seed shows this notification
http://puu.sh/ff2kV/fa78d4e2f8.png
After that, the game crashes to the main menu

**Comment by Dysoch** [comment]
shouldnt happen, but will make sure that in the next version this wont happen

**Comment by Dysoch** [comment]
this shouldnt happen anymore. if it does, make a new issue
