### ISSUE TITLE
Error when planting Rubber Seed. Second Encounter (CORE 1.1.0)

### ISSUE THREAD

**Issue by GameveD** [Dysoch/DyTech#250]
And it's happening again
"When planting Rubber Seed shows this notification"
http://puu.sh/ffHPv/c46779b535.png

I am seem like I'm doing something wrong
I installed:
  Factorio 0.11.13
  DyTech:
    CORE 1.1.0
    Machine 1.0.1
    Power 1.0.0
    War 1.0.0
That's all

**Comment by HastemaNS** [comment]
I have this problem too. Some time i can plant rubber without this problem, but if i load game and come to rubber i have this error again.

If i click on button "ok" game is out to main menu, but if i use esc button error closing and i can play.

**Comment by hrompik** [comment]
I have this problem too. https://www.dropbox.com/s/bov06t702oof1wt/FACT.png?dl=0 
Factorio 0.11.13
DyTech:
CORE 1.0.1
Machine 1.0.1
Power 1.0.0
War 1.0.0

if press ESC i can play but seed not grow.

**Comment by Lycrus** [comment]
Same problems. Seed doesnt grow, in fact whole treefarm doesnt properly work when i get this error. nothing grows -,-

**Comment by tobyas** [comment]
I inserted the following code into lines 73, 101 and 128:
if seedTypeLookUpTable==nil then populateSeedTypeLookUpTable() end
thats the position the error is reported at. This instantiates seedTypeLookUpTable. Though its probably better to instantiate it once in OnLoad, if thats possible.

**Comment by EurypteriD192** [comment]
This error also occours with Sulphur saplings

**Comment by HastemaNS** [comment]
Thx tobyas, i added: 

	if seedTypeLookUpTable==nil then
		populateSeedTypeLookUpTable() 
	end

After :  

game.onevent(defines.events.onbuiltentity, function(event)
local player = game.players[event.playerindex]
	if not remote.interfaces["treefarm_interface"] then
	if event.createdentity.type == "tree" then
	debug("tree created (player "..tostring(event.playerindex)..")")

And trees growing, but i dont sure about correct this fix. Sorry for my terrible english, not my native.

**Comment by tobyas** [comment]
I'm not that familiar with Lua and the mod code but I think, it would be best if seedTypeLookUpTable is instantiated once. So you should probably add it to the onload function. 

game.onload(function()
[...]
	if seedTypeLookUpTable==nil then populateSeedTypeLookUpTable() end
end)

Should probably create a pull request...

**Comment by HastemaNS** [comment]
Yes, you are right. This checking on all planting will create unnecessary loading machine.

But method game.onload working only on loading or saving your savegames how i can see with debug information. Not on create game. Also, this method working on all auto saving. This also initiate much more that once.

**Comment by tobyas** [comment]
Good to know thank you. Didn't think about init. Though it is still loaded only once, since its checks before loading. (if seedTypeLookUpTable==nil then).

**Comment by HastemaNS** [comment]
No no, all autosaving on game will initiate onload too, check it - swith false to true

debug_master = false -- Master switch for debugging, shows most things!

and

game.onload(function()
	if not remote.interfaces["treefarm_interface"] then 
	debug("Treefarm not installed")

"Treefarm not installed" to your randome text, and wait when game autosaving, message will appear

**Comment by Dysoch** [comment]
You can wait till tomorrow :)

I should have fixed them all already. Just gonna test a bit more

**Comment by Dysoch** [comment]
The problem was a bit of left over code from the old treefarm. Check the latest commit i made to see what i did

**Comment by HastemaNS** [comment]
Thx, Dysoch! It good news. Of course, we can wait, just want to play factorio with your mod right now. :laughing:

**Comment by Dysoch** [comment]
Should be fixed with the latest release
