### ISSUE TITLE
game crashe after starting a world

### ISSUE THREAD

**Issue by humbug98** [Dysoch/DyTech#251]
When i start my world a message come that i need more viedeo memory but this is only when i activat
the DyTech-Machine mod the other mods run perfekt but i can not play with this mod please help

Intel core i 5 4790 k |Geforce gtx 970| 8 gb ram

**Comment by Dysoch** [comment]
Then turn on low graphics mode to compensate. There is nothing i can about this, except moving all graphics to tinted base game graphics, but they are bad looking. I find the hand tinted colors much nicer.
