### ISSUE TITLE
Error when saving a game

### ISSUE THREAD

**Issue by Verdat** [Dysoch/DyTech#252]
I'm getting this error whenever i try to save my game

Error while running the onload: __CORE-DyTech-Core__\control.lua:45: Error when running interface function treefarm_interface.addSeed: __Treefarm-Lite__\interfaces.lua:10: attempt to index local 'seedInfo' (a nil value)

It came up after i installed treefarm mod.
IT happens in single player

EDIT: 

Mods i'm using:

Dytech core, Dytech machine, Dytech power and treefarm lite.

System Specs:

Windows 7
i5-3570k
8gb RAM
Gigabyte radeon hd 7870 WIndforce OC

**Comment by Verdat** [comment]
For some reason, i had downloaded eaelier version 1.0.1. In dytech core 1.1.0 this bug is fixed.

**Comment by Dysoch** [comment]
this happens also with installing treefarm in a game in progress.
