### ISSUE TITLE
Solved. No resin drops Dytech 1.1.0, Factorio 11.13

### ISSUE THREAD

**Issue by EurypteriD192** [Dysoch/DyTech#253]
Started a new world after updating Mashine and Core to 1.1 (no other mods)
After removing what is worth 1000+ Wood i have yet to recieve the first resin.

Tried to scout around to see if i could find free growing trees. 
Is the way to recieve the Resins changed?

**Comment by Scorpi** [comment]
![](https://cloud.githubusercontent.com/assets/969654/5994041/88cd58ea-aa76-11e4-9667-0b06e500008f.png)

**Comment by ddayver** [comment]
http://i.imgur.com/CRCutC7.png

**Comment by ddayver** [comment]
:+1: :snail:

**Comment by EurypteriD192** [comment]
Oh i see. Ill close this then thanks and sorry for false bug report
