### ISSUE TITLE
No LavaPools after Update from 1.0.0 to 1.0.1

### ISSUE THREAD

**Issue by sofalord** [Dysoch/DyTech#254]
No LavaPools after Update from 1.0.0 to 1.0.1 after doing the MasterSwitch thing.

all Lava Pools disappear, all metals are on normal on the map.
its a savegame from 1.0.0 . (not playable in 1.0.1 or 1.1.0 cause of the blastfurnace change)

its playable but not at all :(

installed mods now : 
CORE-DyTech-Core_1.1.0
Landfill_2.1.2
MAIN-DyTech-Machine_1.0.1
MAIN-DyTech-Power_1.0.0
MAIN-DyTech-War_1.0.0
Treefarm-Lite_0.1.2 (for the rubber issue)

**Comment by Dysoch** [comment]
I will make an remote call to regenerate the lava. Closing issue, as it is an duplicate of #231 (kind of)
