### ISSUE TITLE
seedTypeLookUpTable Error Still Occuring

### ISSUE THREAD

**Issue by gothroach** [Dysoch/DyTech#258]
As per issue #249, I'm creating a new issue.  I received this error earlier today in 1.0.1, found out it was fixed in a later version.  I upgraded to 1.1.1, but after a few hours of playing I get the same error.

![dytechseederror](https://cloud.githubusercontent.com/assets/678417/6033410/28b356c6-abca-11e4-8785-877c1451f42d.png)

I'm running dytech-core, dytech-war, dytech-power, and dytech-machine.  No other mods are loaded.

**Comment by shadowpho** [comment]
Same here. Playing multilayer with 4 players. Planting resin seed displays error\crashes game for other 3 players.

**Comment by Shadddo** [comment]
I get the error too. its always after I install the core and save the game

**Comment by SuicidalKid** [comment]
Weird. I'm not getting it anymore.

**Comment by HastemaNS** [comment]
I have this problem also when try plant trees :(

**Comment by SKleen75** [comment]
I use Core 1.1.1 and i get this.
![image](https://cloud.githubusercontent.com/assets/10866480/6061091/d1a1204e-ad44-11e4-8dab-0445465a5a4f.png)

**Comment by SKleen75** [comment]
Ok. I embarrassed myself now.
I used an old treefarm zip. It works perfectly with Treefarm-lite and Treefarm-AC 0.1.2.
Sorry.

**Comment by shadowpho** [comment]
Weird. I have no treefarm and it still breaks when planting seeds in MP...

**Comment by mmhvd** [comment]
I get this same error when planting a rubber seed. I had been so delighted to finally figure out how to get those seeds, now this happens... I'm running Factorio 0.11.15 with Core 1.1.1, Power 1.0.0 and Machine 1.0.1.

**Comment by gothroach** [comment]
I can confirm that the Treefarm-Lite mod stops the crashing, even in multiplayer.  There does need to be something that says Treefarm-Lite is required, unless this behavior is unintentional.

**Comment by Dysoch** [comment]
Treefarm is optional, it was a bug on my side. Fixed it with the newest version (hope for good now :D)
