### ISSUE TITLE
Some repo management problems

### ISSUE THREAD

**Issue by Scorpi** [Dysoch/DyTech#264]
Hi Dysoch!
Including version number in folder name and bumping it brokes git history, so we can't easily browse commits. We need to solve this problem.

For now, you have all modules and stuff in one repository, that is not good.
My suggestion is to create separate repos for each module.
That will allow us to control changes, and support code better.
Also we can create download page based on GitHub Pages.

**Comment by Dysoch** [comment]
I thought about it already many timrs, but in the end i always decided to keep it in 1 repo.

But i can make it easier in 2 ways

1. I can rename all modules back to just their name, but this makes it a little bit harder for me to test them easily.

2. I can do the folder name change in 1 single commit, without any code change. I just name the commit something like: folder namr change. 
This way you can browse more easily and ignore those commits

Seperate repos is a hassle to work with unfortunatly

**Comment by Scorpi** [comment]
We can do something like build script. It will give you folders named with version, specially for testing.

**Comment by Dysoch** [comment]
i will revert back to the old name (without the version number behind it.)

Will use a syncing program with different folders to test stuff :D
