### ISSUE TITLE
Construction Robot MK1 doesn't use Advanced Repair Pack

### ISSUE THREAD

**Issue by thc133** [Dysoch/DyTech#266]
I have some Construction Robot MK1 in an isolated Roboport (not Roboport MK1) without connecting other Roboport.  They don't repair buildings with Advanced Repair Pack.  They use only Repair Pak instead.  Is it a bug?

**Comment by ddayver** [comment]
Hm... from mod:

"Advanced Repair Pack that can only be used by Construction Robot Mk 1
Highly Advanced Repair Pack that can only be used by Construction Robot Mk 2"

**Comment by thc133** [comment]
Yeah, the mod said "Advanced Repair Pack that can only be used by Construction Robot Mk 1". However Construction Robot Mk 1 actually uses only Repair Pack, not Advanced Repair Pack.

**Comment by ddayver** [comment]
Tested. My Construction Robot Mk 2 refused to repair the tank, although were available 50 Highly Advanced Repair Pack and 10 Construction Robot Mk 2. Most likely a bug.

**Comment by ddayver** [comment]
MAIN-DyTech-Machine_1.0.1\prototypes\construction-robots\
line 175:
    repair_pack = "repair-pack",
replace
    repair_pack = "repair-pack-2",

line 352:
    repair_pack = "repair-pack",
replace
    repair_pack = "repair-pack-3",

**Comment by thc133** [comment]
It works fine now after modifying entity.lua.  Thanks a lot.
