### ISSUE TITLE
Errors saving map

### ISSUE THREAD

**Issue by cheics** [Dysoch/DyTech#267]
To reproduce:

1. Download save game and mod package
    * https://drive.google.com/file/d/0B_bYPYks2AnNZzJqY2FqVlpFTzQ/view?usp=sharing
2. Add a long inserter in such a way that it can hold COAL (beside the furnace)
3. Allow the long inserter to pickup coal
4. Try to save, get "Can't save map, entity list of entities staged for update of links is not empty" error
![factoriobug](https://cloud.githubusercontent.com/assets/904633/6141762/28afa7f2-b178-11e4-9158-42d15a6c4a1d.png)

**Comment by Dysoch** [comment]
make a bug report for factorio itself. This is not something i can fix
