### ISSUE TITLE
Dytech-Core breaks bobores lead

### ISSUE THREAD

**Issue by hohounk** [Dysoch/DyTech#268]
Bobores mod makes lead give both nickel and lead (3 nickel per 4 lead).
Dytech-core overrides lead ore and nickel can't be mined from lead after that.

The code it uses to make them spawn both is in his data.lua:68:
`  table.insert(data.raw.resource["lead-ore"].minable.results,{type="item", name="nickel-ore", amount=1, probability = LeadNickelRatio})`
LeadNickelRatio is 0.75

It's a configurable option in bobsores and the flag that decides if nickel is given by lead is in config.lua:17:
`-- if set to true, Galena ore fields will give Nickel ore as well as Lead ore.
GalenaGivesNickel=true`

He used to call his lead galena and probably didn't bother to change the names.

**Comment by Dysoch** [comment]
gonna be fixed with a resource mod that is being worked on by 3 mod owners (bob, mcguten and me)
