### ISSUE TITLE
Bullet shooting speed research

### ISSUE THREAD

**Issue by Marduke** [Dysoch/DyTech#271]
There is misleading comment for bullet shooting speed of sniper rifle. let me show
LVL | Speed | bonus by research comment
0     | 1         | 0
1     | 1 + 0.1| 20%
2     | 1 + 0.2| 20%
3     | 1 + 0.3| 30%

on level 3 it should be 1 + 0,2 + 0,2 + 0,3 = 1,7 but it is only 1,3. Where is problem comment of research or real speed value?
This research contains also speed for Submachine gun and pistol, there are good values as percentage of research says.

**Comment by Dysoch** [comment]
not really something i can fix. the setup internally is exactly the same, so it works as expected
