### ISSUE TITLE
Sand cant move by logistic robot

### ISSUE THREAD

**Issue by Marduke** [Dysoch/DyTech#274]
I cant find sand in material list, so i cent move it by robots. I am blind or it is disabled cause of sand is used in too much to transfer this way?

But it is same situacion for smart inserters

**Comment by SuicidalKid** [comment]
It should be under DyTech Intermediates. I'm able to move sand with my bots.

**Comment by Marduke** [comment]
I dont have it in DyTech intermediates, but i am using v0.11.15 and latest github source...
In v0.11.13 it is the and there i used DyTech Core 1.1.1 release

**Comment by Marduke** [comment]
in last version working, bug fixed thx
