### ISSUE TITLE
Modules not working in Electric Furnaces (Mk II)

### ISSUE THREAD

**Issue by maiar-morghulis** [Dysoch/DyTech#275]
I can't insert any modules (tested up to Level 4 of each Speed, Productivity and Efficiency) into the Electric Furnice Mk II. 
Inserting them into the Mk I worked, higher levels of Furnace are maybe affected as well, but still untested. The in-game text plainly reads "Effectivity Module 1 can't be used in Electric Furnace Mk II" (when using the Eff-Module 1).

Factorio version: core-linux-11.16
Installed Mods: DyTech-Core 1.1.1, DyTech-Machine 1.0.1, DyTech-Power 1.0.0, DyTech-War 1.0.0, DyTech-Dynamics 1.0.0, Treefarm-Lite 0.1.3

**Comment by Tristitan** [comment]
you can, you just have to do the control click on the building, you cant place them in from the menu

**Comment by maiar-morghulis** [comment]
hmm, doesn't work for me. Control-click with the modules gives no feedback (not even an error message). 

Quick-Replacing an old Mk I Furnace works, the modules stay in the new furnace - but then you are restricted to the 2 module-slots the old furnace had.

**Comment by SuicidalKid** [comment]
> inserting this list of allowed effects into the code for every electric furnace in factorio/mods/MAIN-DyTech-Machine_1.0.1/prototypes/electric-furnaces/entity.lua fixed the issue

This.

**Comment by Dysoch** [comment]
this is odd, because the allowed_effects line is already there

**Comment by Dysoch** [comment]
fixed it just after previous release, but never released the fix. will be today then :D
