### ISSUE TITLE
Fatal error while loading mods upon loading game upon update to 11.7

### ISSUE THREAD

**Issue by Llewdyn** [Dysoch/DyTech#280]
Using all Dytech mods switched to active and Treefarm mod.
Error while loading entity prototype "radar-mk2" (radar): No such node (max_distance_of_nearby_sector_revealed)
Modifications: Dytech-Automation

**Comment by cdeath** [comment]
I get this error with only dytech mod and the 11.7.

**Comment by SuicidalKid** [comment]
The new update allows mods to change the active view of radars. DyTech hasn't incorporated this feature (yet!) so the game doesn't know what to do and just crashes.

**Comment by Peach774** [comment]
max_distance_of_sector_revealed was replaced with
max_distance_of_nearby_sector_revealed

Just add replace the 2nd with the first and it will work.

**Comment by cdeath** [comment]
where does that get changed?  I tried changing the radar entity and the error still persists.

**Comment by Dysoch** [comment]
look here : https://github.com/Dysoch/DyTech/commit/e506a803d693c4378819a7623db52eb599ba47cc#diff-a66fdad1cdfb2ce00ff92e00baa312a9R27

**Comment by Peach774** [comment]
How would I fix this asap for my game, instead of waiting for a release?

**Comment by Cheata** [comment]
Peach 744

in 

MAIN-DyTech-Machine_1.0.1.zip\MAIN-DyTech-Machine_1.0.1\prototypes\radars

open the entity.lua file

add the line 
max_distance_of_nearby_sector_revealed = 5,
just below the line that reads
max_distance_of_sector_revealed = 20,

for each instance of a radar (ie mk1 mk2 mk3 etc)

the max distance of NEARBY sector ( the new line) controls the immediately visible area where as the max distance of sector controls the area that gets scanned sector by sector so if you want you can now increase the immediately visible range of each level of radar
