### ISSUE TITLE
CORE-DyTech-Core 1.1.2: (data.lua): basic_string::_S_construct null not valid

### ISSUE THREAD

**Issue by penguineer** [Dysoch/DyTech#287]
I tried the CORE-DyTech-Core from github HEAD on Factorio 0.11.17 and got the following error message on loading:

    27441.117916  Info ModManager.cpp:205: Loading mod CORE-DyTech-Core 1.1.2 (data.lua)
    27441.122978  Error Util.cpp:43: basic_string::_S_construct null not valid

**Comment by SuicidalKid** [comment]
Github DyTech builds are not stable. Please download from the forums:
http://www.factorioforums.com/forum/viewforum.php?f=43

**Comment by penguineer** [comment]
I know. This is not a complaint but a pointer to an existing problem. :)

**Comment by Dysoch** [comment]
i havent even tried Core with the new additions i already did :D I dont think it should work yet 
closing issue, since it is not really a bug, but just unfinished work :P
