### ISSUE TITLE
MAIN-Dytech-Machines_1.0.1  -  Radar issues

### ISSUE THREAD

**Issue by XxN4BxX** [Dysoch/DyTech#290]
upond loading the game 0.11.17 aparently there is a line missing in all radars code:
max_distance_of_nearby_sector_revealed
i know that there is a line:
max_distance_of_sector_revealed
both lines are required, i just dont know from what game version onwards that second line is needed though

**Comment by SuicidalKid** [comment]
It's included in 11.17, where they allow radars to be all-around better.

**Comment by Dysoch** [comment]
same as #280 closing this issue since that issue is still open.

It is already fixed, and will be released tomorrow (march 11th)
