### ISSUE TITLE
Can't make very fast inserter by Assembling Machine.

### ISSUE THREAD

**Issue by coelun** [Dysoch/DyTech#291]
Assembly machine can't to put the same by inserters.
Very fast inserter recipe in MAIN-DyTech-Machine_1.0.1
----
1st fast inserter <- OK can put in Assembling Machine by inserter.
2nd fast inserter <- NG cant put in Assembling Machine by inserter.
 :
---
plz next version remake recipe.
http://gyazo.com/bf45e82ef2367828a7a3e1e726d676d4

**Comment by Cheata** [comment]
simple solution to this one is remove the 2nd inserter and set the 1st to 2 required... existed in the old version of dytech too
