### ISSUE TITLE
Car Causes Crash on load with factorio version 0.11.18

### ISSUE THREAD

**Issue by Cheata** [Dysoch/DyTech#292]
latest version of factorio changes the crash damage multiplyer to  energy to hit point

easy fix while waiting for Dysoch to produce a new version :)
 in  MAIN-DyTech-Machine_1.0.2\prototypes\cars\entity.lua
line 56  (under the setup for car2)
change 
crash_damage_multiplier = 0.1,
to 
energy_per_hit_point = 1,

and for the tank 
MAIN-DyTech-War_1.0.1\prototypes\tanks\entity.lua
somwere around line 12 seems to work

add the line
energy_per_hit_point = 0.5,

**Comment by MIZTigerForLife** [comment]
Also experiencing this issue. The above fix allows factorio to load. Thanks for the temporary workaround.

**Comment by nrich61** [comment]
so cars seems to work, but when I do the tanks fix I get this

![factorio](https://cloud.githubusercontent.com/assets/11513438/6680667/6df8af00-cc28-11e4-9da2-75c735f3f46f.jpg)

If i don't do the tanks fix I get this 
![factorio 2](https://cloud.githubusercontent.com/assets/11513438/6680725/03cbc698-cc29-11e4-81d1-f3d516a91f99.jpg)

**Comment by L3PO** [comment]
Hello nrich61,
write the line so:

![to help](https://cloud.githubusercontent.com/assets/11520469/6687179/81cd2e5e-cca8-11e4-853f-8223ebf48202.jpg)

**Comment by Cheata** [comment]
looking at my copy of the file in question i would guess that you are either putting the energy per hit point line after the "stack size =1" line,  if this is the case you need to leave the comma off the energy_per_hit_point line and add it to the end of the stack size line.

or possibly you are mistakenly deleting the }, which exists around line 13,  without looking at your modified file i cant say specifically what the mistake is.

simplest solution is to do it exactly as L3PO has done it in his screen shot above

**Comment by L3PO** [comment]
@Cheata, thanks for the tip, notepad2 is very helpful.

**Comment by Dysoch** [comment]
fix for release of next version tomorrow around noon (UTC +1)
