### ISSUE TITLE
Multiplayer crash with new dynamics beta

### ISSUE THREAD

**Issue by binary101010** [Dysoch/DyTech#294]
(I know its not optimized for MP yet, hope the report helps anyway)

Installed newest MAIN-DyTech-Dynamics from Release Page + Factorio 11.18.

/scripts/rs-functions.lua (line 16 + 24) is using the player object (instead of the players array?) and causes a crash when trying to unlock a recipe in multiplayer mode.

**Comment by Cheata** [comment]
binary101010
as a temporary workaround 
try changing the 2 mentioned lines from 

game.player.force.recipes[Name].enabled = true
to 
game.players[1].force.recipes[Name].enabled = true

if that works then its probably approaching the correct code although there may also be some code needed to either force the recipes on the other players or select the correct ones

note i haven't tried this it just seems like the the correct direction based on the error
of course this code will probably need to be changed for every player connecting to your game to prevent desync issues ???

**Comment by binary101010** [comment]
Added a new function to enable the recipe and called it with foreach, this worked for the unlocking part.
After that we encountered some nil and other index out of range errors, i guess we will just wait for a actual MP release...

Really nice Mod btw :+1:
