### ISSUE TITLE
Personal laser defense

### ISSUE THREAD

**Issue by Dadelius** [Dysoch/DyTech#295]
I have no clue if the shootingspeed is diffrent but the dmg from tier 2 is higher than the tier 3 what looks strage. 
![unbenannt](https://cloud.githubusercontent.com/assets/9332150/6667269/40836976-cbeb-11e4-88b9-a46d29928c42.png)

EDIT: after a check i have to say the tier 3 does less dmg with the same shootingspeed so that should be a bug

**Comment by Dysoch** [comment]
fixed
