### ISSUE TITLE
Missing recipe for clean-iron-ore and clean-copper-ore

### ISSUE THREAD

**Issue by Hobbyte** [Dysoch/DyTech#297]
The centrifuges are cleaning iron and copper ores, but it's impossible to smelt them!

**Comment by SuicidalKid** [comment]
I thought this was intentional, so I had set up a huge facility to melt them into liquid iron/copper... All that work for nothing I suppose :(

**Comment by Dysoch** [comment]
Oops. Will be fixed tomorrow with the release!

**Comment by Dysoch** [comment]
fixed

**Comment by Hobbyte** [comment]
Thanks!
