### ISSUE TITLE
Error while loading entity

### ISSUE THREAD

**Issue by mini-man** [Dysoch/DyTech#298]
Mods:
DyTech Script 1.0.0
Dytech dynamics 1.0.0
Dytech Core 1.1.3
Dytech Machine 1.0.2
Dytech Power 1.0.1
Dytech War 1.0.1
Base Factorio 11.18

When I launch the game with any mod excluding the dytech core and base, it comes up with a error saying
"Error while loading entity prototype "car2" (car): No such node
(energy_per_hit_point)

On WINDOWS

**Comment by Dadelius** [comment]
https://github.com/Dysoch/DyTech/issues/292 same problem, this hotfix might help you. but next time take a few moments to take a look in this github to check if the problem already is known

**Comment by mini-man** [comment]
Thank you. I did have a look in lots of places for the issue but didn't find it. Might look harder next time.
