### ISSUE TITLE
Balacing suggestions (from the forum)

### ISSUE THREAD

**Issue by SvenDee** [Dysoch/DyTech#299]
Suggestions for balancing:

War:
Laser Turrets:
Silver Ruby : Increase damage from 5 to 5.5 (or something like this). At this moment the Silver Ruby is useless because of same damage per second and range but energy consumption increased by 33%. thx to thc133 for making this clear.

Laser gun battery: Mk1 MK2 are the same? MK3 less damage then 1&2? should be fixed
the same happend to the personal laser defence mk3 less damage as the mk2. so maybe this is a bug.

Centrifuge: - time to make a plate of clean ore is longer as with dirty one, need to be fixed. should be same or shorter.( because with clean ore its easier to make one plate ) recipes added with new version, so thats great..
- 3 stone for 1 ore? thats to much. we generated 125k stone in a few hours with that. 1 stone should be fine or fragments like iron and copper.

**Comment by Dysoch** [comment]
Laser Turrets are have had their recipes changed, and the first laser turret (bronze ruby) is now weaker (by 1/4th, so they start with 3.75 dmg instead of 5)

Rest of balancing suggestions will be implemented soon

**Comment by Dysoch** [comment]
all fixes implemented!
