### ISSUE TITLE
Multiplayer does not work v0.11.18

### ISSUE THREAD

**Issue by codebyt3r** [Dysoch/DyTech#301]
Hello,

multiplayer is not working atm. Player 2 desync always after he has downloaded the map.

 Factorio v0.11.18

**Comment by codebyt3r** [comment]
I just looked if i got the new updates - I got an old version of the mod I will download the newest and try again.

**Comment by Dysoch** [comment]
By not supplying any information i cant fix this. Supply info, and i might be able to fix it, providing it is an issue with DyTech

**Comment by codebyt3r** [comment]
It works now. I reinstalled the game and the mod on both pcs.
