### ISSUE TITLE
Gem Mining suggestion

### ISSUE THREAD

**Issue by Cheata** [Dysoch/DyTech#304]
Would it be worth changing the gem mining system so that instead of producing 10 different resources it outputs a "Gem-Ore"

The different outputs could then be divided out in the first gem processing/crushing step
i.e gem ore in ->>        maby water in if slurry output??
<<- crushed emerald out
<<- crushed ruby out
<<- crushed diamond out
<<- crushed sapphire out
<<- crushed topaz out
<<- stone/slurry out

Thoughts please :)

**Comment by SuicidalKid** [comment]
It would certainly help with inventory clutter, I'm all for it!

**Comment by MagicLegend** [comment]
Well, first of all, this belongs on the forums. Please put it under the 'ideas & suggestions' topic (http://www.factorioforums.com/forum/viewtopic.php?f=43&t=2816). Github is for bugs only.

**Comment by Dysoch** [comment]
actually suggestions can be made here as well. That i dont mind. But the idea is ok, but i will do it differently with a new item called crystals
