### ISSUE TITLE
I cant use:

### ISSUE THREAD

**Issue by hasezoey** [Dysoch/DyTech#306]
I cant use in the forge 9x iron-plate i cant find the picture 
![factorio 2015-04-20 19-32-47-61](https://cloud.githubusercontent.com/assets/10911626/7236331/96be1e66-e794-11e4-8ab9-04d2a334ba5a.jpg)
![factorio 2015-04-20 19-32-33-11](https://cloud.githubusercontent.com/assets/10911626/7236350/b2d7ee6a-e794-11e4-8415-3bd078142048.jpg)
![factorio 2015-04-20 19-32-34-90](https://cloud.githubusercontent.com/assets/10911626/7236364/c7b1c5c2-e794-11e4-8cbb-2ea7997c7cb0.jpg)

Please Fix the bug :(

Game Version: 0.11.21

**Comment by Dysoch** [comment]
not a bug

that is a recipe from Fmod, which can only be used in the Fmod variant of the forge, not the DyTech one.
