### ISSUE TITLE
DyTech-Machine 1.0.3 can't be run at 4k (3840x2160)

### ISSUE THREAD

**Issue by Serverfrog** [Dysoch/DyTech#308]
As the title Says. 
When DyTech Machine 1.0.3  and DyTech-Core 1.1.3 are installed, the Game can't be resize to 4k (3840x2160 pixels). When this is done, the Game Crash with the error
Unable to create sprite (3836X2066) probably not enough of video memory.

Here is the Error Log

PC Specs, to confirm that the PC Specs are not the real problem here.
 - Windows 8.1 Version 6.3.9600 Build 9600
 - Inter Core i7-37770K@ 3,50 GHz
 - 16 GB RAM
 - nVidia GeForce GTX 970
 - Displays
   - Main Display
      -  http://www.iiyama.com/gb_en/products/prolite-b2888uhsu-b1/
      - 28"
      - 30 Hz
      - Native Resolution: 3840 x 2160
   - Secound Display
      - Acer B273H
      - 27"
      - 60 Hz
      - Native Resolution: 1920 x 1080

```
   0.001 2015-04-30 14:20:08; Factorio 0.11.22 (Build 14011, win32)
   0.001 Operating system: Windows 8 
   0.002 Read data path: C:/Program Files (x86)/Factorio/data
   0.002 Write data path: C:/Users/m-p-h_000/AppData/Roaming/Factorio
   0.002 Binaries path: C:/Program Files (x86)/Factorio/bin
   0.091 Initialised video: NVIDIA GeForce GTX 970
   0.143 Graphics options: [FullScreen: false] [VSync: true] [UIScale: 150%] [MultiSampling: OFF] [Graphics quality: normal] [Video memory usage: all]
   0.196 Loading mod core 0.0.0 (data.lua)
   0.209 Loading mod base 0.11.22 (data.lua)
   0.420 Loading mod CORE-DyTech-Core 1.1.3 (data.lua)
   0.651 Loading mod MAIN-DyTech-Machine 1.0.3 (data.lua)
   1.031 Loading mod base 0.11.22 (data-updates.lua)
   2.155 Initial atlas bitmap size is 16384
   2.158 Couldn't create atlas bitmap (size 16384x10185), will try again
   2.169 Created atlas bitmap 8192x8185
   2.540 Created atlas bitmap 8192x8185
   2.684 Created atlas bitmap 8192x4181
  12.172 Info Updater.cpp:717: Downloading https://www.factorio.com/updater/get-available-versions?username=Serverfrog&token=<private>&apiVersion=2
  13.073 0 packages available to download (experimental updates disabled).
  13.109 Factorio initialised
  21.663 Loading map 
  21.664 Info Scenario.cpp:158: Map version 0.11.22-0
  21.711 Info LocaleProvider.cpp:114: Using locale files from the pre 0.11.0 structure (__CORE-DyTech-Core__/script-locale/en.cfg)
  24.917 Error Util.cpp:43: Unable to create sprite (3836X2066) probably not enough of video memory.
  27.212 Goodbye
```

**Comment by Dysoch** [comment]
send this error to the devs of the game. There is nothing i can do with this.
the problem is with bitmap, and that is mostly a vram issue

**Comment by MagicLegend** [comment]
A bit late to react, but i think your 970 is the problem. It's vram is just too small to run unoptimized games (like factorio) in 4K. You'll have to poke the developers about the way textures are loaded, we are unable to do anything about this.
