### ISSUE TITLE
"Laser Turret" vs "Bronze Ruby Laser Turret"

### ISSUE THREAD

**Issue by roy7** [Dysoch/DyTech#309]
Some parts of the UI call the basic laser turret the old name, and some use the new name.

**Comment by Dysoch** [comment]
know the issue, will be fixed

**Comment by Dan-Gecko** [comment]
Can you push a fix please? Or tell me, what to change. I tried to alter the recipe in War_1.0.2\prototypes\turrets-laser\recipe but it did not change anything ingame (maby I'm missing on something out).
