### ISSUE TITLE
Problems loading any Dytech mod folders with factorio v0.11.22

### ISSUE THREAD

**Issue by TaintedDragon** [Dysoch/DyTech#310]
Any time I launch factorio with any Dytech mods installed I get prototype errors. With just the Dytechcore 0.13.3 I get a science pack 1 ID error. Can anyone help with these prototype errors?

**Comment by MagicLegend** [comment]
There is no dytech core 13.3.0. Maybe you are using the

**Comment by TaintedDragon** [comment]
This would probably be my problem because I couldn't find the Dytech downloads anywhere and after an hour of searching I found downloads on dropbox so thats just what I used.

**Comment by Dysoch** [comment]
yes. Everything has merged into 4 modules, instead of 10. They are the most up to date versions for now (release of next version should be in a week or so)
