### ISSUE TITLE
Science liquid crafting bug

### ISSUE THREAD

**Issue by Marduke** [Dysoch/DyTech#311]
science pack 1 from liquids have same ingredients as lab from liquid, probably missed after copy/paste
5.3 sludge
9 liquid iron 
11,3 liquid copper 
is too much - normal recipe is
1 copper
1 stone

**Comment by codewarrior0** [comment]
Seems to be fixed in bfe3bd45ef7082d8b68719973ddaead60800b989

**Comment by Marduke** [comment]
yes, this issue should be marked as fixed
