### ISSUE TITLE
Forges produce until stack is full

### ISSUE THREAD

**Issue by codewarrior0** [Dysoch/DyTech#314]
After the change that made the mold stay in the Forge after crafting, when crafting recipes that only require fluids, the Forge will keep crafting until it has an entire stack in its output slot.

When molds had to be reinserted into a Forge, the inserter logic would stop reinserting molds when the output slot has 2 or more outputs in it. Now, the Forge has the same behavior as the Chemical Plant does when producing Sulfur - as long as liquids are supplied, it keeps producing until the stack is full.

This is in fact the default behavior of assembly and other machines. The inserter logic is what stops the machine from overproducing when the outputs are not collected. I can't think of a way around this right now.

**Comment by codewarrior0** [comment]
For my game, I just reverted the mold change and did the usual thing with smart inserters.

**Comment by Dysoch** [comment]
not gonna look at this. This is behavior that i expected, and dont mind, Stacksize isnt that high, so a few items more made isnt bad :D (resources are infinite anyway)
