### ISSUE TITLE
Game crashes when loading mods

### ISSUE THREAD

**Issue by Humanhead** [Dysoch/DyTech#316]
I'm using a clean installed Factorio 0.12.0 and no other mods. My OS is Win7 64bit
i get these errors when loading the Dytech Power and the Dytech War mods:

![factorio dytech bugreport](https://cloud.githubusercontent.com/assets/13437190/8804567/1e9a02b6-2fcd-11e5-8395-d7374990ed71.png)

**Comment by Slakto** [comment]
For the power error, reloaded it, should fix the issue. :)
War is incompatible with Treefarm-AC, I just posted about it also. :)

**Comment by Humanhead** [comment]
thanks for the quick reply, it works now!
