### ISSUE TITLE
War incompatible with Treefarm-AC

### ISSUE THREAD

**Issue by Slakto** [Dysoch/DyTech#317]
Getting the error: 
_MAIN-DyTech-War_/data.lua58:
_MAIN-DyTech-War_/prototypes/turrets-flame/entity.lua:26: attempt to call global 'gun_turret_extension' (a table value)

Removing either Treefarm-AC or DyTech-War resolves the issue.

**Comment by Dysoch** [comment]
i suspect i has to do with his glue turret, will look into it

**Comment by Dysoch** [comment]
Ok looked at it, its Treefarms fault. he edits the gun_turret_extension.

Will speak with drs9999

Closing issue as it is not my fault :D
