### ISSUE TITLE
Power - /control.lua:5 module gui.gui not found;

### ISSUE THREAD

**Issue by DreamSmith** [Dysoch/DyTech#318]
Power - /control.lua:5 module gui.gui not found
no such file -Power _ _/gui/gui.lua 
no such file [Factorio]/data/core/gui/gui.lha

No mods but Dytech core, machines, power and war active.  Game loads but this error when clicking generate.

**Comment by Dysoch** [comment]
there is a temp fix here:
http://www.factorioforums.com/forum/viewtopic.php?f=43&t=1563&p=93058#p93057

**Comment by Humanhead** [comment]
rename the GUI folder from uppercase to lowercase "gui" in the MAIN-DyTech-Power_1.1.0.zip

**Comment by DreamSmith** [comment]
Confirmed fix.  Will upload at midnight if Dysoch hasn't.
