### ISSUE TITLE
dytech-war_data.lua:58

### ISSUE THREAD

**Issue by Picard44** [Dysoch/DyTech#323]
![factorio](https://cloud.githubusercontent.com/assets/13442523/8814618/ca110978-300e-11e5-9f67-10e17fa6fb4d.png)

Mods installed (all for version 0.12):
DyTech-core
DyTech-war
DyTech-power
DyTech-machine
treefarm-ac
treefarm-lite
fluid-void

Cant load factorio with mod DyTech-war. It's working without war mod.

**Comment by Bonsai555** [comment]
You can load DyTech-War  if you leave out the treefarm modules.

**Comment by Tristitan** [comment]
you can also do a work around and put a optional dependency for dytech warfare in treefarm ac, this will force treefarm ac to load first which will stop the error

**Comment by Bonsai555** [comment]
Could you commit this "work around" here too? Not everyone knows how to change dependencies.
Or you could describe how it is done and also how it is undone.

**Comment by JLBShecky** [comment]
Well the workaround that I used for the moment was editing "Treefarm-AC_0.2.0\prototypes\ammoPrototypes.lua" and replacing all instances of "gun_turret_extension" with "gun_turret_extension_ac" although any such change of the variable name would work.

**Comment by Bonsai555** [comment]
Thanks!

**Comment by Picard44** [comment]
Thanks for your help, guys. JLBSheckys solutions is doing fine :)

**Comment by JLBShecky** [comment]
I can't really take credit for it as I just looked at the fix that Dysoch posted over on the Treefarm thread and took a few seconds to implement it on my end. :D
