### ISSUE TITLE
Starting prerequisites... 

### ISSUE THREAD

**Issue by JLBShecky** [Dysoch/DyTech#326]
Ok so I have noticed a couple of things at the beginning of the game that are unlocked be require that you research technologies before you can build them. The ones that I have noticed so far:

High Pressure Boiler - it requires that you have tin processing unlocked.
High Powered Steam Engine MK I - need steel gears which require steel processing.

Also I noticed that at least the starting engines are showing up in the opposite order of their boiler matches, namely they engines go *high->normal* and the boilers go *normal->high*.

**Comment by MagicLegend** [comment]
Hmm. Interesting. Thank you for reporting. Will go on my to-do list for tomorrow. I'll close the issue once I've committed an fix.
