### ISSUE TITLE
planting seeds causes crash

### ISSUE THREAD

**Issue by AnarConn** [Dysoch/DyTech#328]
not much more to say than the topic and attaching a screenshot
![ss 2015-07-22 at 03 30 40](https://cloud.githubusercontent.com/assets/13452537/8826643/491857b6-3088-11e5-8f7c-80ad6673aee2.jpg)

**Comment by Bonsai555** [comment]
This issue has just beed closed a few hours ago.
https://github.com/Dysoch/DyTech/pull/325
