### ISSUE TITLE
Tree seed crash

### ISSUE THREAD

**Issue by morp007** [Dysoch/DyTech#329]
When i try plant seed game crashes
![dytech bug](https://cloud.githubusercontent.com/assets/12032247/8834665/9a283c14-30c6-11e5-9123-a0a3adf69a3c.jpg)

**Comment by Bonsai555** [comment]
Hey morp007 before posting an issue, you should at least have a look if this issue/bug has already been reported or even solved yet. In this case it is the 3rd post with this bug and it already has been fixed.
#325

**Comment by morp007** [comment]
i'm noob in github and didn't see filter "is:open" X_X
