### ISSUE TITLE
Liquid Handler produces dirty water instead of clean water

### ISSUE THREAD

**Issue by Silverpolo** [Dysoch/DyTech#331]
Tooltip is right, but it's not working.

Thanks.

**Comment by MagicLegend** [comment]
DYSOCH! Next time please dont change the way the dirty and clean water works one hour before the release...

**Comment by Dysoch** [comment]
:D

**Comment by Silverpolo** [comment]
All recipies I encountered thus far require dirty water, didnt notice that when I posted the comment ;-)

**Comment by Dysoch** [comment]
its works at my place when using a savegame from 0.11.

it appears the reset command didnt fire.
Either keep playing with the savegame, or start a new one :D
