### ISSUE TITLE
Unknown key: "entity-name.small-lamp-1" and others

### ISSUE THREAD

**Issue by Toudi2** [Dysoch/DyTech#332]
Research "Optics 1" unlocks another lamp called Unknown key: "entity-name.small-lamp-1"

The vanilla lamp is unlocked by researching "Optics"

**Comment by Dysoch** [comment]
true, forgot it.

same is with lamp-2, beacon-1, beacon-2. and beacon-3
already on to do list for next version

**Comment by bumbasher** [comment]
also "modifier-description.sniper-ammo-damage-bonus"
