### ISSUE TITLE
Centrifuge Processing 2 also unlocks Centrifuge

### ISSUE THREAD

**Issue by Toudi2** [Dysoch/DyTech#333]
Both "Centrifudge Processing" and "Centrifudge Processing 2" unlocks Centrifudge. Is this intended ?

Also the two research have the same tooltip. Shouldn't the first one have something different in the tooltip ?

**Comment by MagicLegend** [comment]
Fudge <3

Ps. Sorry, I couldn't unread the sentence. My head really was like fudge?! I want!! Also, it will go on Dysoch's to-do list ;-)

**Comment by bumbasher** [comment]
It seems to be really minor issue

**Comment by MagicLegend** [comment]
It is, but it's something that needs some fixing.
