### ISSUE TITLE
World Gen Error Factorio 0.12.0

### ISSUE THREAD

**Issue by Duros1394** [Dysoch/DyTech#336]
Hey there I've just downloaded and installed a fresh factorio 0.12 with the latest DyTech modules.
However upon generating a new map I get the following error:
__MAIN-Dytech-Power__/control.lua:5:module gui.gui not found; no such file
__MAIN-Dytech-Power__/control.lua no such file
__MAIN-Dytech-Power__/control.lua no such file
C:/Program Files/Factorio/data/core/lualib/gui/gui.lua

Thats all that pops up on the Notice screen. the world then doesn't generate and i'm stuck on generation options.

If trying to load a 11.22 world it mentions an error with train rails then immediately quits.

**Comment by JLBShecky** [comment]
This issue has already been fixed see #318.

**Comment by MagicLegend** [comment]
Sorry! Its indeed fixed. Happy playing!
