### ISSUE TITLE
No high powered steam engines Mk2+

### ISSUE THREAD

**Issue by ReallyAngryHamster** [Dysoch/DyTech#338]
Hi, I cannot find any high powered steam engiens Mk 2+. There are only the basic ones. I don't know if it's intentional, but there are high powered boiler for all marks.

**Comment by JLBShecky** [comment]
Looking over things it seems that although the engines are being defined in game they are never being unlocked by their respective techs.

**Comment by MagicLegend** [comment]
Ehm... That is my module, isn't it? Hehe...

Looked over. Sorry 'bout that! Dysoch and I are working on an new way to handle techs internally. Once that's done, an new version of power will air, with a bunch of fixes.

**Comment by ReallyAngryHamster** [comment]
Yay, thank you very much for your work!
