### ISSUE TITLE
0.12.0 with Dytech - Crash to desktop 

### ISSUE THREAD

**Issue by TrippinLF** [Dysoch/DyTech#341]
Not sure if this problem is due to the Dytech Mod (I have posted the same report to the factorio bug report forum) or not. However... 

I have the following mods installed: 

MAIN-DyTech-War_1.1.0
MAIN-DyTech-Machine_1.1.0
MAIN-DyTech-Power_1.1.0
CORE-DyTech-Core_1.2.0
AlienSeed_0.4.0
Treefarm-Lite_0.2.0

(should hopefully be links to savegame and log file somewhere in this post.) 

Savegame:
https://www.dropbox.com/s/cqmdl7ja0w8wu46/dytech12.zip?dl=0

Logfile:
https://www.dropbox.com/s/mmj6je4eqmzsty5/factorio-current.log?dl=0

When I try to attack the base towards the north east, it crashes to desktop. No other behaviour (other then a brief pause while it crashes), or messages. Just a straight CTD. Have tried approaching from various different angles and changing the active attack robot, but it doesn't seem to matter. Not sure what is triggering the crash (the current robot on the save expires about a minute into the save - hence the idea of changing the current robot), but can occasionally get into the middle of the base before the crash. Other times it crashes while kiting round the edge. Have managed to replicate the crash a half dozen times. Haven't tried going swapping out the various mods - but I haven't had any problems with the basic Factorio 0.12.0, and as the game is pretty early on, I haven't built much. 

Any suggestions or fixes?

**Comment by TrippinLF** [comment]
Forgot to leave system spec... 

Win 7 
i7 4700mq
8gb ddr3
Intel HD gfx / GTX 780m (pretty sure Factorio runs on the Intel chip though)

**Comment by MagicLegend** [comment]
I think this is something you should post on the forums about. It doesnt look like something Dytech related. I know TF-AC will not work correctly with dytech war, but I'm not sure in what way it won't.

I'll test your save tomorrow, to see if I have the same issue.

~ML

**Comment by MagicLegend** [comment]
Sorry, my head isnt functioning correctly. I thought you had TF-AC for some reason. Whoops ;-)

**Comment by morp007** [comment]
I have same problem. And that problem comes from dytech_war. When dytech_war disabled - everything goes normal... 
And what strange - "bad" savegame crash happens in the same time whatever i'll do. First time it was on 8:30 (I used clock mod from Bob's mods). I "solve" this problem by loading 6min realtime earlier savegame, but ~2 hours later crash comes again.
Firstly I think it's bug on dyzilla, but it's switched off. Probably problem goes from biters drop? I've played ~13h and some far places just covered in corpses. Another option - I used many belts before walls to auto-collect corpses.
If need - I can upload my logs (it's same with @TrippinLF) and savegame.
P.S. sorry for my terrible english, it's not my native language

**Comment by xGnoSiSx** [comment]
I also have the same crash log. Loaded up the mod with test mode, cheated in some modular armor and modules and started killing bitters. I bult no base and placed no items/building on the map. After some evolution score, I am getting the 'unreasonable chunk' error no matter what I do.

**Comment by TrippinLF** [comment]
@magicLegend - thanks for checking. The report I posted in the main factorio bug report forum got moved to the resolved bug forum - so (big assumption), they have either fixed it, or because of the mods, aren't interested. In either case, I'll restart the game and go from there. 

@morp007 @xGnoSiSx - its nice to know that I'm not alone in having this problem,

**Comment by Dysoch** [comment]
as far as i can see in the log, this is an factorio issue. Please supply the same info to the devs. They should be able to fix it.

**Comment by xGnoSiSx** [comment]
@Dysoch I played 0.12 with no mods for 40 hours and built a huge base on my latest save and had no crashes. You might be passing something tricky with the modding api that causes this?

**Comment by TrippinLF** [comment]
@Dysoch Thank you for checking it through. 

@xGnoSiSx Similar this end. Had a 25hr game with no problems. 


In either case, will try the new 0.12.1 (with Dytech) and see if that's more stable.

**Comment by MagicLegend** [comment]
@Everybody

Bugs are just like clowns. When you expect them the least, they are behind you.

Other way of saying, not every savegame is the same. Bugs are everywhere, even in vanilla Factorio. You might have been lucky by playing 25 hours without crashing, others will crash in an hour. I've played Dytech for +-40 hours now, and have never crashed.

Supply this info on the forums, they might be able to help.

~ML

Ps. Still need to test the save, whoops ;-)

**Comment by Dysoch** [comment]
closed this, it seems a factorio bug. If not, open a new issue
