### ISSUE TITLE
Issues with dytech advanced gun turret and others

### ISSUE THREAD

**Issue by Toudi2** [Dysoch/DyTech#344]
Advanced Gun Turret seems to be out of ballance: it seems they have values from factorio 0.11 instead of 0.12

it deals 2 dmg with normal, 5 with piercing ammo and has speed of 6/sec
the factorio 0.12 gun turret deals 4 dmg with normal ammo and 10 with piercing and has speed of 10

unless its intended for it to trade damage for range it seems odd that "advanced" is less powerful.

Plasma gun turret is a bit confusing because its is not clear what ammo it takes. It would be helpful it were at least told in the description. (I still dont know what ammo it takes). The same should be for other turret to better explain what ammo they use.

PS: it would be nice if thoes turrets were researchable

**Comment by Dysoch** [comment]
Those turrets are researchable.

I forgot to add the modifiers.

Plasma gun turret uses the same ammo as the plasma gun, and the plasma shotgun turret uses the same ammo as the plasma shotgun
