### ISSUE TITLE
File not Found

### ISSUE THREAD

**Issue by max2605** [Dysoch/DyTech#345]
Dytech can't find a File...

My Mods all newest Version:
Dytech
UraniumPower
Youkio

![bug](https://cloud.githubusercontent.com/assets/13490359/8886188/fdeeb7d6-3266-11e5-96ec-12a565398877.PNG)

**Comment by bumbasher** [comment]
I think this has already been fixed see #337 and #318

**Comment by MagicLegend** [comment]
It is. Derpy things happen when power is zipped
