### ISSUE TITLE
Laser Turrents recipes require basic Bronze Ruby Laser Turrent

### ISSUE THREAD

**Issue by tobyas** [Dysoch/DyTech#346]
The recipes for [Bronze, Silver, Gold] [Ruby, Sapphire, Emerald, ?] Laser Turrents all require a Bronze Ruby Laser Turrent. I think in the previous versions they needed the previous version of the turrent in order to upgrade it (bronze -> silver -> gold).

**Comment by Dysoch** [comment]
true, but this has been changed to use the base laser turret to be a bit cheaper. Only the topaz and diamond turrets now require the emerald turrets. 

Not a bug
