### ISSUE TITLE
Cannon Turrets and shells range

### ISSUE THREAD

**Issue by ReallyAngryHamster** [Dysoch/DyTech#347]
Cannon Turret has range of 50, but both normal and explosive cannon shells have range of 30. In practice the turret shoots at biter at 50 range, but the shell explodes mid-way to the target. So they are practically useless.
Other thing that maybe intentional is that the projectiles explodes on collision with everything. So if you put your turret behind the walls, which you probably need in Dytech, the shells will destroy the walls instead of biters.

**Comment by Dysoch** [comment]
This is really base game behavior. To explain:
The base game adds the projectiles, which have a collision. What that means, when shot, it hits the first thing they reach. 

This is really behavior that i like, and requires you to change your layout to work with this.
Not an issue in my eyes

(PS, There is an armored version of it, and you can place that in front of the walls )
