### ISSUE TITLE
High powered boilers upgrade balance?

### ISSUE THREAD

**Issue by ReallyAngryHamster** [Dysoch/DyTech#348]
Currently high powered boiler require 3 same level normal boilers. So if I build a Mk 2 high power boiler, I cannot upgrade it directly. I have to go: Normal boiler Mk.I -> Normal boiler Mk.2 -> High power boiler Mk.2 . The problem I see is that at this point I can just throw high power boiler Mk. I away. 
So in a case when I have High power Mk.4 boilers and want them make Mk.5, I must go all the way from the beginning.
To me, it does not seem worthy, Resources-wise I might just double the amount of boilers and stick to low power ones.

**Comment by MagicLegend** [comment]
Good point. Might change this for the next bugfixrelease.

~ML
