### ISSUE TITLE
The super fast DyTech inserters are not working

### ISSUE THREAD

**Issue by xGnoSiSx** [Dysoch/DyTech#349]
From Buggi in the general discussion forums:

For some reason the super fast DyTech inserters are not working. They can be crafted and placed, but do not move. I have no idea why. They worked fine in the previous version.

Edit:

The first dytech inserter doesn't work, but the one marked "fast dytech inserter" does work.

**Comment by ReallyAngryHamster** [comment]
Im not quite there yet, but from what I remember, in last version they were smart. They didn't have it in their name, but you could click on them and you had to put filters there.

**Comment by Dysoch** [comment]
I think you misunderstood the inserter. 
In the naming:
DyTech Inserter: This is a smart inserter, and you need to filter it to let it work.
Fast DyTech Inserter: This is an inserter with only connection to the logistic network, and works without filter (you cant filter it)

Names will be changed to make it more clear
