### ISSUE TITLE
Lua error while playing scenario

### ISSUE THREAD

**Issue by Silverpolo** [Dysoch/DyTech#351]
Hiya,

Since I updated to 12.1 I get an error when I want to play the map I just created as a scenario. When creating a scenario I dont get any errors.

As a test I just created one and only put the flag down where I want to start. Saved it and got the following message when I want to play it. Its the same message everytime on different maps. 

![naamloos](https://cloud.githubusercontent.com/assets/13458070/8895163/57e79f36-33d0-11e5-8c11-e8c5f857267b.jpg)

**Comment by Dysoch** [comment]
Fixed this for next version. You can check this commit: https://github.com/Dysoch/DyTech/commit/a1edeee1d2bd79a55184771e505b8377b2349bac
