### ISSUE TITLE
MAIN Dytech Power: Error prevent generating map

### ISSUE THREAD

**Issue by Taurec** [Dysoch/DyTech#353]
I have Factorio 1.12.1 and Dytech Core 1.2.0, Dytech Machine, Power and War Version 1.1.0. Without any other mods, i become this Error, when i try to start a new map:

![dytech](https://cloud.githubusercontent.com/assets/10584350/8895431/6504bec4-33da-11e5-8da4-49d73c97d7fe.jpg)

System Spec:

CPU:           AMD Phenom II X6 1100T (Thuban, PH-E0 (Pharaoh))
               3300 MHz (16.50x200.0) @ 3314 MHz (16.50x200.9)
Motherboard:   GIGABYTE GA-880GA-UD3H
Chipset:       AMD RS880 + SB810/SB850
Memory:        16384 MBytes @ 669 MHz, 9.0-9-9-24
               - 4096 MB PC10600 DDR3 SDRAM - G Skill F3-10666CL9-4GBRL
               - 4096 MB PC10600 DDR3 SDRAM - G Skill F3-10666CL9-4GBRL
               - 4096 MB PC10600 DDR3 SDRAM - G Skill F3-10666CL9-4GBRL
               - 4096 MB PC10600 DDR3 SDRAM - G Skill F3-10666CL9-4GBRL
Graphics:      Sapphire Radeon R9 280X
               ATI/AMD Radeon HD 7970/R9 280X, 3072 MB GDDR5 SDRAM
Drive:         OCZ-AGILITY3, 250.1 GB, Serial ATA 6Gb/s @ 6Gb/s
Drive:         WDC WD10EVVS-63M5B0, 976.8 GB, Serial ATA 3Gb/s
Drive:         OCZ-AGILITY2, 58.6 GB, Serial ATA 3Gb/s
Drive:         TSSTcorp DVDWBD SH-B123L, BD-ROM
Sound:         ATI/AMD Tahiti - High Definition Audio Controller
Network:       RealTek Semiconductor RTL8168/8111 PCI-E Gigabit Ethernet NIC
OS:            Microsoft Windows 8.1  (x64) Build 9600

**Comment by MagicLegend** [comment]
Please check git if your problem already exists. Also, boo for the AMD card ;-)

Ps. Fix the problem by changing in dytech-power the GUI folder to gui (upper to lower case), that will fix the problem.

**Comment by Taurec** [comment]
Thanks, your solution works. :)
I'm sorry, but i haven't seen any post, which doubles my problem? 

What do you have against my AMD Card? Tz Tz. *g*
