### ISSUE TITLE
Capsules do no damage.

### ISSUE THREAD

**Issue by Oninaig** [Dysoch/DyTech#354]
Was playing multiplayer using the following:

-CORE-Dytech-Core_1.2.0
-MAIN-Dytech-Machine_1.1.0
-MAIN-Dytech-Power_1.1.0
-MAIN-Dytech-War_1.1.0
-Factorio 0.12.1

When trying to use the various damaging capsules (we specifically tested the Poison, Acid, and Napalm), they do no damage to biters or biter spawners (in the case of Acid as I thought Acid damaged structures). Spoke with you on Slack about it and you confirmed it was a bug and you wanted me to post it here.

**Comment by Toudi2** [comment]
Fix failed.

I'v tested your fix and it does not work. The only thing you changed was to remove affected_by_wind .

I compared the poison entity with the base game and discovered that the type has changed from "smoke" to "smoke-with-trigger".

When I changed the type in your poison-cloud-1 and poison-cloud-2 it worked.

**Comment by MagicLegend** [comment]
I think I've fixed it with my newest commit.
