### ISSUE TITLE
Can't clean ore in centrifuge except copper and iron

### ISSUE THREAD

**Issue by Silverpolo** [Dysoch/DyTech#355]
Ola,

It doesnt clean any of the dytech ores.

Thanks for looking into this.

**Comment by MagicLegend** [comment]
It works for me. Can you give some more info about what isnt working? (Not being able to select the recipe in the centrifuge for example)

**Comment by Silverpolo** [comment]
Hmm, ok. Exactly that. Cant select recipe in centrifuge.

**Comment by Silverpolo** [comment]
Did a clean install. Removed everything. Works like a charm now. Sorry for the extra ticket ;-)
