### ISSUE TITLE
Spitter Range

### ISSUE THREAD

**Issue by tobyas** [Dysoch/DyTech#356]
There seems to be a bug with spitter range. Don't really know how to reproduce it but I had a spitter destroy parts of my base from the oppsite of a lake. I also have one of those green cloud thingies destroying stuff in my base without a spitter in sight. I have a savefile for this if it would help?

**Comment by Dysoch** [comment]
not needed, know what is causing this. Was talking to somebody else about this:

that is not really a bug. With 0.12 there is a rudimentary support for pvp, and with me changing the projectliles of the spitters to have collisions (so they are no longer homing, but hit the first thing they hit) i might have made this an extra feature
I like it, and i think it fits in with dytech
Once they fire at you, but hit an biter or spitter, they will attack each other :)

The projectiles fly across the map, so they can hit other stuff 2

**Comment by Dysoch** [comment]
if people dont like this feature i can remove it. But this feature fixed 1 issue, that projectiles from spitters are always homing, this is no longer the case :D 
if you move fast enough, you can dodge them
