### ISSUE TITLE
Power throwing an error on worldgen

### ISSUE THREAD

**Issue by ljcomplex** [Dysoch/DyTech#359]
Okay, so when I go to start a new world, with a fresh install of 0.12.1, and fresh installs of the DyTech mods, Factorio throws this error: Picture Below
__MAIN-DyTech-Power__/control.lua:5: module gui.gui not found; no such file __Main-DyTech-Power__/gui/gui.lua no such file__Main=DyTech-Power__/gui/gui.lua no such file C:/Users/LJ/Desktop/DyTech/Factorio_0.12.1/data/core/lualib/gui/gui.lua

I'm not at all sure where this is coming from. 

Mods:
All Dytech mods except Dynamics
Landfill 2.1.5
Larger Inventory 1.0.0
Treefarm lite 0.2.0 (Tried with and without, this version said it fixed the DyTech issue, no change)
Fluid Barrel 1.0.0

Specs: 
Processor: Intel Core i7-4500U CPU @ 1.80GHz 2.40 GHz
RAM: 8GB
System: 64-bit Windows 8.1
Video: Nvidia FeForce GT 745M
![dytecherror](https://cloud.githubusercontent.com/assets/8717655/9001724/574d1a4c-3718-11e5-9339-a9ae1e984329.PNG)

**Comment by Dysoch** [comment]
already reported in #353, #352 and 2 more issues.

Its has been fixed already, and will be released soon.
