### ISSUE TITLE
DyTech Power throwing an error during worldgen

### ISSUE THREAD

**Issue by ljcomplex** [Dysoch/DyTech#361]
![dytecherror](https://cloud.githubusercontent.com/assets/8717655/9011339/f45eb2cc-3769-11e5-8a28-7ea193471ded.PNG)
So when I start a new game with fresh installs of Factorio 0.12.1 and DyTech, I get this error. No idea how to fix this. 

Processor: Intel Core i7-4500U CPU @ 1.80GHz 2.40 GHz
RAM: 8GB
System: 64-bit Windows 8.1
Video: Nvidia FeForce GT 745M

Mods: 
Greenhouses 0.1.0
landfill 2.1.5
Fluid Barrel 1.0.0
Larger Inventory 1.0.0
DyTech Mods:
Core 1.2.0
Machine 1.1.0
Power 1.1.0
War 1.1.0

**Comment by Dysoch** [comment]
This is report 10 or so about this, and its already fixed!

**Comment by ljcomplex** [comment]
Oh! I didn't see anything about it. How do I fix it?

**Comment by ljcomplex** [comment]
Sorry! Never used Github before, so I didn't see the closed section. I'll take a look at the ones you linked in my last one.

**Comment by Dysoch** [comment]
Go into the zip file, and open the control.lua
There you will find:
require "gui.gui"
require "gui.functions"
at line 5 and 6.
Rename them to this:
require "GUI.gui"
require "GUI.functions"
that should fix the problem
