### ISSUE TITLE
module gui.lua missing - FIX: rename GUI to gui (caps)

### ISSUE THREAD

**Issue by physonic** [Dysoch/DyTech#362]
Downloaded MAIN-DyTech-Power_1.1.0 from factorio forum 01/08/2015 17:30 GMT+1
Error on map load: missing module gui/gui.lua
i renamed the folder called GUI to gui and map loaded fine. maybe it was renamed in caps in error.

**Comment by MagicLegend** [comment]
Correct. Whoever made it case sensitive should give up their job ;) It's already fixed in devbuilds, just not the public version yet.
