### ISSUE TITLE
Bag for Power

### ISSUE THREAD

**Issue by arx691** [Dysoch/DyTech#366]
![default](https://cloud.githubusercontent.com/assets/1975238/9034283/e078cba0-39e7-11e5-8d13-7e1ee58d0cb7.jpg)

**Comment by MagicLegend** [comment]
Could you please give some additional information? What mods are you using, which version of Factorio?

**Comment by arx691** [comment]
Veris used to GitHub , and only yours. sorry for my english

**Comment by arx691** [comment]
found an error

91:	elseif Config.Small_Accumulators and Config.Large_Accumulators and not Normal_Accumulators then
		require("prototypes.accumulators.tech.small_and_large")

91	elseif Config.Small_Accumulators and Config.Large_Accumulators and not Config.Normal_Accumulators then
		require("prototypes.accumulators.tech.small_and_large")

**Comment by Toudi2** [comment]
Indeed there is an error in Power data.lua line 91: you missed the "Config."

the line should be as arx691 said:
91 elseif Config.Small_Accumulators and **Config.**Large_Accumulators and not Config.Normal_Accumulators then

**Comment by MagicLegend** [comment]
This is something that Dysoch committed. It is not my work. I'd prefer not to have it, because it will break old savegames appearantly, but it's not really my mod so yeah ;-)

**Comment by MagicLegend** [comment]
Also, you guyes shouldnt be using the code from github, because it is experimental and unstable. This is something you can expect when doing so.

**Comment by Dysoch** [comment]
Actually it MIGHT break your savegame. I tested 10 savegames, and only 1 was corrupted. Might have something to do with the change, might not
