### ISSUE TITLE
oil-processing-1 and oil-processing-2 aren't shown in tech list

### ISSUE THREAD

**Issue by ArgLuna** [Dysoch/DyTech#368]
I saw new oil refinery and chemical plant were added in dytech machine v1.1.0 (Released: July 21th 2015).

But I tried to unlock technology in normal way (whithout commands), and use console command to enable all technologies, there's no new oil refinery or chemical plant in recipe list. Besides, both of oil-processing-1 and oil-processing-2 weren't shown in the technology list.

The mods I used were only dytech packs(included core, machine power and war). Also confirmed that machine.config.Oil_Upgrades = true.

I think the problem might be that related files are not required in data.lua and  there need some other code.

P.S.: game version: 0.12.2

**Comment by ArgLuna** [comment]
I found a solution that just correct line 353 in data.lua
require("prototypes.lamps.tech") -> require("prototypes.chemical-plants.tech")

**Comment by Dysoch** [comment]
Has already been fixed at the master branch
