### ISSUE TITLE
Problem & Error Notice Splash When starting game.

### ISSUE THREAD

**Issue by Cooolaid** [Dysoch/DyTech#370]
Here is an image that shows you have Capital Letters on the "GUI" folder.
and the (.lua) file is looking for the folder with lower case letters of (gui) folder.
this throws a error splash screen saying it can not find the (required) loading of file request coming from (control.lua)

Re-editing the GUI folder to lower case letters (gui) folder fixes the problem.
Just want you to know. :)

http://i.imgur.com/Wk1q3cn.jpg

**Comment by Timeslice42** [comment]
I can confirm this issue as well.

**Comment by vlczero** [comment]
This is already fixed and reported already #353 ;)

**Comment by MagicLegend** [comment]
Please check if your problem already exists.

Bugfix will come later today (+-5PM GMT+1)
