### ISSUE TITLE
research_all_technologies command issue

### ISSUE THREAD

**Issue by MrMaleficus** [Dysoch/DyTech#374]
Hello,
I've this error when i try to turn on all technologies after the beginning of the game (i like this type of gameplay)

<img width="1040" alt="capture d ecran 2015-08-09 a 17 23 57" src="https://cloud.githubusercontent.com/assets/5609863/9155545/89a2578c-3ebb-11e5-8e3e-0e732232e20a.png">

**Comment by Dysoch** [comment]
use the button in the dytech debug menu for now.
couldnt find a solution real fast, so made a work around
