### ISSUE TITLE
cant start maps (power missing gui.lua)

### ISSUE THREAD

**Issue by Skillabstinenz** [Dysoch/DyTech#375]
i updated to factorio 0.12.2 64bit
with mods:
dytech:
core 1.2.1
machine 1.1.1
power 1.1.0
war 1.1.1
then this error turned up, both for loading old games but also for new ones too:
<a href="http://www.directupload.net" target="_blank"><img src="http://fs2.directupload.net/images/150809/xzoqurys.png" title="Kostenlos Bilder und Fotos hochladen"></a>

if i deactivate the power mod it works, i can even use things from the power mod.

![bugged](https://cloud.githubusercontent.com/assets/845260/9155813/1ad6c752-3ec5-11e5-90d4-b8bfbb1db15c.png)

**Comment by RegDenied** [comment]
Go into the zip file, and open the control.lua
There you will find:
require "gui.gui"
require "gui.functions"
at line 5 and 6.
Rename them to this:
require "GUI.gui"
require "GUI.functions"
that should fix the problem

See here:
#352 #353 #359 #361

**Comment by jamesjames** [comment]
works, thx.
