### ISSUE TITLE
Error gui error

### ISSUE THREAD

**Issue by vyasmonarchu** [Dysoch/DyTech#376]
Having this error popup when starting a new game. All the options are left to factory settings.

Other Mods used along with Dy-tech are posted in picture itself

also the screenshot of error is posted in image
![untitled](https://cloud.githubusercontent.com/assets/13736803/9182125/08b46f2c-3f77-11e5-8e60-9a62f7a40bbf.jpg)
![untitled1](https://cloud.githubusercontent.com/assets/13736803/9182351/2364a8fe-3f78-11e5-9fd5-d295b1b92df5.jpg)

**Comment by RegDenied** [comment]
See here:
#352 #353 #359 #361 #375
