### ISSUE TITLE
Steam engine research only unlocks high-powered primary?

### ISSUE THREAD

**Issue by Oninaig** [Dysoch/DyTech#388]
I saw in the tech tree that the HP stream engine researches were listed as only unlocking the primary high-powered version of that level and that the regular steam engine research was only unlocking the secondary steam engines of that level. Example of what you unlock when you get all tech:

![factorio 2015-08-14 18-47-24-847](https://cloud.githubusercontent.com/assets/2964006/9285588/62ebb112-42b5-11e5-845c-0f42109047a0.png)
![factorio 2015-08-14 18-47-29-597](https://cloud.githubusercontent.com/assets/2964006/9285591/6a57a1ea-42b5-11e5-846a-f36e7d008caf.png)
![factorio 2015-08-14 18-47-32-781](https://cloud.githubusercontent.com/assets/2964006/9285595/6eaaa5da-42b5-11e5-88a1-aced7cad6d1f.png)

Is this intended?

**Comment by Dysoch** [comment]
Intended Feature. 
You can change the output of your "normal" steam engines by standing next to it and using the dytech power gui. Be care full, its not MP compatible, only singleplayer. MAgiclegend made some errors while making the code. 
You can take the latest Power from github and that is now MP compatible
