### ISSUE TITLE
Portable Solar Panel Mk 2 output to low

### ISSUE THREAD

**Issue by Selmephren** [Dysoch/DyTech#392]
The portable solar panel mk2 is listed as 30W of output, mk1 is 1kW and mk3 is 9kW.  Should the mk2 be 3kW and not 30W?

**Comment by Dysoch** [comment]
update to latest War which has been released. Its already fixed

**Comment by Selmephren** [comment]
Version 1.1.1 released 8 Aug still has bug, only github files hold fix.
