### ISSUE TITLE
Disabling high-steam-engines break startup

### ISSUE THREAD

**Issue by sadris** [Dysoch/DyTech#398]
Setting "Config.High_SteamEngines = false" makes Factorio complain: 

`    Error in assignID, 'high-steam-engine-primary' was not recognized id of recipe`

**Comment by MagicLegend** [comment]
Hmm, I get an different error... I'll fix the ones that I'm getting, hopefully it'll fix yours as well.

**Comment by MagicLegend** [comment]
Fixed (sorry for the delay). It was an really stupid copy-paste derp. Will be fixed in the next release.
