### ISSUE TITLE
Accumulator MK6 recipe

### ISSUE THREAD

**Issue by kghost** [Dysoch/DyTech#399]
Small/large accumulator MK6 only requires MK5\*5, but normal one also requires MK4\*5

BTW: I/O of MK6 is lower than MK4/5, is it Intended ?

**Comment by MagicLegend** [comment]
The last thingie is intended, because it holds an button of energy.

The recipe isnt intended tho, need to look at that. I wanted to make them cheaper, so they become useable.

**Comment by MagicLegend** [comment]
https://github.com/Dysoch/DyTech/releases
