### ISSUE TITLE
Smart inserters - wire networks

### ISSUE THREAD

**Issue by kingofzeal** [Dysoch/DyTech#401]
I'm attempting to use some of the mods smart* inserters, but noticed that you cannot connect wires to them. 

It looks like the mod entities are missing a couple definitions: circuit_wire_connection_point and circuit_wire_max_distance, which are on the base smart inserter. When I add these elements in manually, everything seems to work well. They may also need to be added to the modded smart chests (I haven't checked them yet).

**Comment by MagicLegend** [comment]
Is this fixed?

**Comment by Dysoch** [comment]
Uuuh yes, latest release already had this build in
