### ISSUE TITLE
solar-panel-secondary wrong function call

### ISSUE THREAD

**Issue by camarril** [Dysoch/DyTech#403]
In "\MAIN-DyTech-Power_1.1.1\prototypes\solar-panels\normal\entity.lua" line 28, 
you call the wrong function, I guess. 
It should be "SolarPictures()", not "BaseSolarPictures()".
The "solar-panel-secondary"graphic is 4x4 otherwise.

**Comment by MagicLegend** [comment]
function BaseSolarPictures(Scale) 
41 return 
42     { 
43       filename = "__base__/graphics/entity/solar-panel/solar-panel.png", 
44       priority = "high", 
45       width = 104, 
46       height = 96, 
47 	  scale = Scale 
48     } 
49 end 
From "\MAIN-DyTech-Power_GITHUBVERSION\prototypes\functions.lua" from line 40 onwards. This uses the base-picture, which is the one that should be used for the tier 1. I think this isnt an bug, it is an feature ;)
