### ISSUE TITLE
Power v1.1.1 doesn't load

### ISSUE THREAD

**Issue by Timeslice42** [Dysoch/DyTech#406]
When data.lua tries to require the hightech boilers on line 31, it crashes because prototypes\boilers\tech\highTech.lua calls a function that doesn't actually exist.

**Comment by Timeslice42** [comment]
Note that this issue doesn't exist if I have the War and Machine 1.1.1 mods installed. Or it was fixed with the recent 1.3.0 Core (this issue was occuring with the older 1.2 core).

**Comment by MagicLegend** [comment]
I dont have the issue with the newest version of the mods. My devbuild is built against only the core, without the other modules. This testing is done before an release.
