### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by flexoo** [Dysoch/DyTech#407]
I updated core to 1.3.0 and the game doesn´t even come to load and closes with error: 
CORE-DyTech-Core/locale/de/DyTechModularToolLocales.cfg(1): '='
character not found in line

**Comment by Dawider10** [comment]
You have to add "=" in DyTechModularToolLocales.cfg file in first line between "item-name" and "]"

**Comment by flexoo** [comment]
aah, too easy^^ solved my problem, thanks for your help :)

**Comment by Dawider10** [comment]
No problem ;)
