### ISSUE TITLE
Error on Save.

### ISSUE THREAD

**Issue by tmoore79** [Dysoch/DyTech#409]
![error](https://cloud.githubusercontent.com/assets/2943557/9578887/ba5bfd34-4fe5-11e5-8361-6b8af999dd60.jpg)

**Comment by tmoore79** [comment]
Version: Factorio 0.12.5
Mods: Dytech,Yugi Industries + Yugi Addon Engines, Side Inserters, Compressed Chests. Void Pipes.

**Comment by Dysoch** [comment]
already fixes with latest release
