### ISSUE TITLE
Order of laser turret researches is messed up.

### ISSUE THREAD

**Issue by Quizer85** [Dysoch/DyTech#411]
[(DyTech War 1.1.1]

The order of the laser turret research topics seems out of whack. Not sure if it is meant to be a single chain or a fork, but it seems like single chain was intended. However, Laser Turrets 2 and Laser Turrets 3 both seem to require Laser Turrets 1, with Laser Turrets 4 following on Laser Turrets 3 and Laser Turrets 2 becoming a dead end. I think this is because in the tech.lua, the order is l-t-3 for both Laser Turrets 3 and 4, but the second line at the top also seems weird / superfluous.

**Comment by Dysoch** [comment]
Fixed
