### ISSUE TITLE
Assembly Machine 6 Recipe

### ISSUE THREAD

**Issue by gixbit** [Dysoch/DyTech#414]
Hello, I have searched for this issue on this github repository and I cannot find it. There seems to be an extra requirement and spot for the purple circuits. This is making it impossible to automate these. Not a big deal for me atm on my world but, Thought this was a bit weird.

![19](https://cloud.githubusercontent.com/assets/3877176/9610238/cc3f2814-50b2-11e5-9791-a6c181da451e.png)

**Comment by Dysoch** [comment]
report it to Bob :D 
my recipe is fine, he changes it in way that you get more ingredients that needed, the processing unit is an example. This might happen with more recipes. But its nothing i can fix for my side.
