### ISSUE TITLE
Lava pool with insane high rate/sec and higher temperature than others

### ISSUE THREAD

**Issue by Halothreefan** [Dysoch/DyTech#419]
Hey, 

Found this lava pool that has a weird number instead (171706) of a percentage. When i use a Geothermal Extractor, it will give 859000/sec with a temperature of 1400 while a normal pool has something like 5-10/sec with a temperature of 600. 

Included the map string as well, just walk south at the 3 lava pools, it's the left one.
![dytech lava pool3](https://cloud.githubusercontent.com/assets/9633462/9857784/f9357fd4-5b1c-11e5-8241-46988e68b9e3.png)

Mods:
Treefarm AC 0.2.1
Treefarm Lite 0.2.0
Farl 0.4.0
Dytech Core 1.3.0
Dytech Machine 1.1.1
Dytech Power 1.1.1
Dytech War 1.3.0
DefaultRequestAmount 1.0.0

Map Exchange string:
>>>AAAMAAcAAwADAxEAAAAKAAAAYXJkaXRlLW9yZQMDAgQAAABjb2Fs
AQQDCgAAAGNvYmFsdC1vcmUDAwIKAAAAY29wcGVyLW9yZQEFAwkAAAB
jcnVkZS1vaWwDAwIKAAAAZW5lbXktYmFzZQMDAgkAAABnZW1zdG9uZX
MDAwIIAAAAZ29sZC1vcmUDAwIIAAAAaXJvbi1vcmUBBQMIAAAAbGVhZ
C1vcmUDAwIFAAAAbWFnbWEDAwIPAAAAbWV0YWxsdXJneS1vcmVzAwMC
CgAAAHNpbHZlci1vcmUDAwIFAAAAc3RvbmUBBAMHAAAAdGluLW9yZQM
DAgwAAAB0dW5nc3Rlbi1vcmUDAwIIAAAAemluYy1vcmUDAwLRSB2sYG
UAAH23AAAAAAAAAAAAAAMAykT3ag==<<<

System Info:
Linux 32bit Ubuntu 14.04 1GB of Ram

Data Dump:
http://wikisend.com/download/438974/DyTech.zip

**Comment by MagicLegend** [comment]
Intended. It's an feature.

**Comment by Halothreefan** [comment]
Ok thanks for the info

**Comment by Dysoch** [comment]
yes please. Could you do a data dump and send the script-output folder to me? It gives some relevant info about your configs, and some ingame logs

**Comment by Halothreefan** [comment]
Ok have the link of the data dump http://wikisend.com/download/438974/DyTech.zip

**Comment by Dysoch** [comment]
now that i see the picture (stupid windows 10 is still a bit buggy and have some problems with graphics drivers) i see that everything is working as at should.

its not 859.000 p/sec. its a total deposit of 859.000 lava with the temp of 1400. Its not infinite like the other, its finite. This is an intended features for now (its already removed from the main github repo with the balance)

closing issue

**Comment by Halothreefan** [comment]
Ah ok that makes sense, thanks for the help
