### ISSUE TITLE
Error at start with latest power v1.1.2

### ISSUE THREAD

**Issue by flexoo** [Dysoch/DyTech#423]
When I start and it wants to load the mods, it stops with error that says, it can`t find the file info.json in the zip folder.

**Comment by MagicLegend** [comment]
Ugh, not again... I have no clue where the error is coming from. If you unzip the folder (make sure it's not making an folder inside an folder) it will start working again.

**Comment by flexoo** [comment]
yep, this way it works. But strange error, maybe somewhere misses something that says the file is in there!?

**Comment by MagicLegend** [comment]
I know, i know >.< I dont know if other mod authors have this problem as well, but I seem to be the lucky one to get it at least once every release :p

**Comment by flexoo** [comment]
aah traditions... aren´t they lovely :D

**Comment by MagicLegend** [comment]
Dysoch has informed me that this is an bug in the basegame. I'll close this issue, because there is nothing I can do about it. I'll add an warning to the current release that it needs to be unzipped.

**Comment by exa-byte** [comment]
I had the same issue. I might be wrong, but i think the solution is no problem of the source code, but it is a problem of wrong packaging: Inside the zip is no "MAIN-DyTech-Power_1.1.2" which must contain all the other files. When i changed that, everything worked without unzipping the whole thing. 
Hope i could help
exa

**Comment by Dysoch** [comment]
You are right. There should be a folder inside the zip, and ML knows this. Reopening issue

**Comment by MagicLegend** [comment]
ah, I didn't know that. Lemme fix it.

~ML

**Comment by MagicLegend** [comment]
Should be fixed with release 1.1.3
