### ISSUE TITLE
[0.12.X] Unable to start new world

### ISSUE THREAD

**Issue by hephinator** [Dysoch/DyTech#428]
Factorio: 0.12.15
Modules: Core 1.3.0, Machine 1.1.1, Power 1.1.3, War 1.1.1

Verified that all are latest per forum post, and compatible with 0.12.x (core is 0.12.5+ rest are 0.12.x)

Getting this error on attempt to create a map / start new game: http://puu.sh/l0I5a/ceeac7c7d1.jpg
Mods Folder: http://puu.sh/l0I5P/0a29f427d1.png

I assume this has to due with the changes in 0.12.12+ which require mods to sync game state.

Edit**: Tested, 0.12.10 works, 0.12.11+ are effected by the error described above.

**Comment by RegDenied** [comment]
I have the same issue with only DyTech Core.

**Comment by imhumangetmeoutofhere** [comment]
This happened to me too with exactly the same setup.

**Comment by kabrok** [comment]
Same problem here. Really don't have a clue on what to do to fix it.

**Comment by MagicLegend** [comment]
Dysoch is currently really busy (as usual) with work.

Another user pointed out to me that the issue can be fixed if you remove the control.lua file from the core. This is something I cannot confirm, nor deny, but keep in mind that the mods are not designed to have the control.lua removed.

You can try that, but in the mean time you will have to wait for Dysoch to fix the issues (or me, maybe I'll do it...)

~ML

**Comment by kabrok** [comment]
Thanks for the info MagicLegend. I'll test and report here ASAP.

**Comment by kabrok** [comment]
Okay. When i deleted control.lua from the core, other errors apeared. It ended up like this:

- Delete control.lua from EVERY file. (Core, Machine, Power and War). You probably will be able to start a map without any errors.

I really don't know if deleting all "control.lua" will have any significative impact on gameplay.

**Comment by MagicLegend** [comment]
Ok, so this isnt true. I know for a fact that deleting the control.lua can lead to a lot of errors, and  you shouldnt do that. I'm sorry that there isnt an fix for now!

~ML

**Comment by kabrok** [comment]
I see. I'll wait for a proper fix then. Thanks.

**Comment by Halothreefan** [comment]
yeah best is to stick with 12.10 for now

**Comment by zlyfire** [comment]
The issue still hasn't been fixed, with the last github edit showing as 21 days ago. Can we have an update on this issue?
