### ISSUE TITLE
filename of found dytech power 1.1.3  Factorio 12.12 any solution?

### ISSUE THREAD

**Issue by evoweek** [Dysoch/DyTech#433]

**Comment by Halothreefan** [comment]
Stay with 0.12.10 because of the mod changes that were introduced in 0.12.11. Dysoch and Magiclegend are very busy so 0.12.10 will have to do for now. I still use 0.12.10 for Dytech and that runs fine. :)

**Comment by MagicLegend** [comment]
Yep, busy days. Power is by the way already 0.12.11+ ready, but core isnt.

**Comment by evoweek** [comment]
it is only not dytech power. all modes give me error msg (case sensitive). i trying 0.12.3 0.12.7 factorio versions. Help me !!!!
