### ISSUE TITLE
[FEATURE REQUEST] Put 0.11.x mods into one packs

### ISSUE THREAD

**Issue by hron84** [Dysoch/DyTech#434]
As I see you moved to 0.12.x but I'm still on 0.11 as I want a relative stable version from the game. Please put 0.11 packs together because I am not able to find the right packs. I read your [listing page](http://www.factorioforums.com/forum/viewtopic.php?f=43&t=6235) about which version matches witch game version, but the zips are not linked to that forum page. I also tried to versions at your Dropbox folder for 0.11, but the latest Core version from Dropbox does not start me complaining about some non-existing science pack.

Please do some cleanup for downloads because - as a new user - I am lost in many-many pages you have and the many-many releases you have without a single, readable download page for each version - or, a single downloadable pack for 0.11 that **works**.

I also recommend you to separate different modules to different GitHub projects as it lets users find a right version of the mods and not requires to dig into a big release archive where so many stuffs hanging around.

**Comment by MagicLegend** [comment]
Hi there,

You need to go on Git to the releases page, and scroll down for an 0.11 version. You can run <0.12.11, those are stable as well.

~ML

**Comment by hron84** [comment]
@MagicLegend which are a 0.11 version? I could not find them easily and your version numbering makes no help me for find them correctly. These "v1.0.2-machine" -like tags are not helping too, and no 0.11/0.12 mentioning in file name or in description.

Please make it easier to find, link them to the README or make a compact one-file package from them because digging in a GitHub release archive is not that friendly that should for.

**Comment by flexoo** [comment]
www.factoriomods.com/mods/dytech

There you can find the zips for 0.11.

Here on github you have to change the branch first (from master to 0.10 or 0.11) 
Just click in the right column on "Code", then you see the actual branch. To change it, click on the menu directly over the Dytech files, <branch: master>.

**Comment by hron84** [comment]
@flexoo thanks for pointing to the right URL. Could you please add it to the README since this URL is not advertised anywhere and quite hard to find.

About GitHub: I changed branch on `Code` tab, but sadly it does not applies to `Releases` tab, that still displays both 0.12 and 0.11 codes in mixed way. That's why I asked my question first since the normal filtering options (on the code) aren't apply to the releases, because they're handled separatedly.

**Comment by flexoo** [comment]
Yeah, sometimes it can be difficult to find the right stuff easy ways. Maybe MagicLegend or Dysoch add it there, just as another - little more convenient - archive for older versions.

**Comment by MagicLegend** [comment]
I'll have a look. Since 0.12 we are using the version in the tag of the release (as you have probably noticed), but for older versions this is not the case. Once I have time for it (Tuesday?) I'll make an forum post with older versions of Dytech.

I think the versions that came before the 0.12 tag are suitable for 0.11. Don't pin me on that one tho. You can check it by opening the info.json within each of the modules.

~ML

**Comment by hron84** [comment]
@MagicLegend I can, but I do not want to download every single zip on the site to check if it is good for me or not. Also, I'm just a player, not a developer, I do not want to check JSON files or these things, just download right stuffs. I think it's not too hard to include a single URL in the README.md to point users (not developers) to proper sites to download your stuffs. I hope you want more and more satisfied users and not more and more frustrated ones.

**Comment by Dysoch** [comment]
I am not supporting 0.11 anymore. You will have to move to 0.12 to use DyTech
