### ISSUE TITLE
Top tier Processing Units have no recipe without metallurgy

### ISSUE THREAD

**Issue by ajranney** [Dysoch/DyTech#440]
Some item recipes call for "Highly Advanced Processing Unit" and "Logic Diamond Processor" however there is not a recipe for these items in the game.  Example items that use these are: Personal Roboports MK2,3, Portable solar panel MK4,5 Energy Shield MK 3,4,5, Battery MK 3,4,5.
MODS:
base 0.12.24
CORE-DyTech-Core 1.9.9
MAIN-DyTech-Machine 1.9.9
MAIN-DyTech-Power 1.9.9
MAIN-DyTech-War 1.9.9

**Comment by Dysoch** [comment]
should be fixed with latest commit
