### ISSUE TITLE
DyTech Power Syntax error

### ISSUE THREAD

**Issue by Pere250** [Dysoch/DyTech#442]
Had a look through and unless I'm blind I couldn't find a like 'issue' with generating a new map.
![screen shot 2016-03-07 at 1 39 08 692am](https://cloud.githubusercontent.com/assets/2888161/13564295/dc5d14a4-e405-11e5-8b46-d8d549f22252.png)
Anything I would be able to do to get it working, or is it a simple issue of version mismatching?
Factorio - 0.12.26
DyTech Power - 1.1.0

**Comment by MagicLegend** [comment]
You need to download dytech from the dropboxlink at the factorioforums. I think this will fix your issue.

**Comment by MagicLegend** [comment]
You can download the newest version of Dytech here:

https://forums.factorio.com/viewtopic.php?f=43&t=6456&p=125225 (scroll down to the last post)

**Comment by Pere250** [comment]
Only download I could find was the torrent >.< Thanks a lot eh, I really was quite blind! Seems to be working fine for the time being been a year. You have my thanks Magic you truly are a legend.

**Comment by MagicLegend** [comment]
Good to hear it worked :-)
