### ISSUE TITLE
Resin smelting

### ISSUE THREAD

**Issue by hasezoey** [Dysoch/DyTech#443]
I cant smelt resin in the furnace , steel furnace , electic furnace to rubber.
is it a bug?

i use dytech core, dynamic, power, war, world and treefarm (from blu3wolf)

**Comment by jasperfennet** [comment]
Got the same issue

**Comment by braven25** [comment]
same issue, so we cant make 'exits' meaning e can make a LOT or different tech :-(

**Comment by NevaDie** [comment]
dont know i can post this here, but the unofficially method at the forum atm is;

to chance the smelting-recipe.lua in the mod archive "CORE-DyTech-Core_1.9.9.zip\CORE-DyTech-Core_1.9.9\prototypes\intermediates"

to 

data:extend(
{
  {
    type = "recipe",
    name = "bone-charcoal",
    category = "smelting",
    energy_required = 2.5,
    ingredients = 
	{
	  {"bone", 1}
	},
    result = "bone-charcoal",
	result_count = 3
  },
    {
    type = "recipe",
    name = "rubber",
    category = "smelting",
    energy_required = 2.5,
    ingredients = 
	{
	  {"resin", 1}
	},
    result = "rubber",
	result_count = 1
  },
}
)



this i my solution but not the best maybe waiting for a patch

Neva

**Comment by hasezoey** [comment]
THANKS :D it works now we can make all :)

**Comment by NevaDie** [comment]
i know this is working i used it myself but its not the perfekt solution
